package bank;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.Objects;

/**
 * The specification for part 1 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Ten tests, and between them they lean on all four pillars.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- encapsulation: the balance can never become illegal --------------
        check("an account rejects a negative opening balance", () ->
            expectThrows(IllegalArgumentException.class, () -> new Account("a", -1)));

        check("deposit increases the balance", () -> {
            Account a = new Account("a", 100);
            a.deposit(50);
            expectEquals(150, a.balanceCents());
        });

        check("withdrawing more than the balance throws and leaves it unchanged", () -> {
            Account a = new Account("a", 100);
            expectThrows(IllegalArgumentException.class, () -> a.withdraw(500));
            expectEquals(100, a.balanceCents());
        });

        check("deposit and withdraw reject non-positive amounts", () -> {
            Account a = new Account("a", 100);
            expectThrows(IllegalArgumentException.class, () -> a.deposit(0));
            expectThrows(IllegalArgumentException.class, () -> a.deposit(-5));
            expectThrows(IllegalArgumentException.class, () -> a.withdraw(0));
            expectThrows(IllegalArgumentException.class, () -> a.withdraw(-5));
            expectEquals(100, a.balanceCents());
        });

        // --- abstraction + polymorphism: transactions apply themselves --------
        check("a Deposit transaction applies through the ledger", () -> {
            Ledger l = new Ledger();
            l.open(new Account("a", 0));
            l.run(new Deposit("a", 200));
            expectEquals(200, l.account("a").balanceCents());
        });

        check("a mixed list of transactions runs through ONE loop (polymorphism)", () -> {
            Ledger l = new Ledger();
            l.open(new Account("a", 1000));
            l.open(new Account("b", 0));
            l.runAll(List.of(
                new Deposit("a", 500),        // a: 1500
                new Withdraw("a", 200),       // a: 1300
                new Transfer("a", "b", 300)   // a: 1000, b: 300
            ));
            expectEquals(1000, l.account("a").balanceCents());
            expectEquals(300, l.account("b").balanceCents());
        });

        check("a Transfer that would overdraw throws and moves no money", () -> {
            Ledger l = new Ledger();
            l.open(new Account("a", 100));
            l.open(new Account("b", 0));
            expectThrows(IllegalArgumentException.class, () -> l.run(new Transfer("a", "b", 999)));
            expectEquals(100, l.account("a").balanceCents());
            expectEquals(0, l.account("b").balanceCents());
        });

        check("each transaction applies itself: apply is the polymorphic call", () -> {
            Ledger l = new Ledger();
            l.open(new Account("a", 500));
            l.open(new Account("b", 0));
            new Deposit("a", 100).apply(l);      // a: 600
            new Withdraw("a", 200).apply(l);     // a: 400
            new Transfer("a", "b", 300).apply(l); // a: 100, b: 300
            expectEquals(100, l.account("a").balanceCents());
            expectEquals(300, l.account("b").balanceCents());
        });

        check("the ledger delegates to the transaction rather than testing its type", () -> {
            Ledger l = new Ledger();
            l.open(new Account("a", 50));
            l.run(new Deposit("a", 25));
            expectEquals(75, l.account("a").balanceCents());
        });

        // --- composition: the ledger owns its accounts ------------------------
        check("the ledger throws for an unknown account", () -> {
            Ledger l = new Ledger();
            expectThrows(NoSuchElementException.class, () -> l.account("nope"));
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. You just used all four pillars.");
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
