package report;

import java.util.List;
import java.util.Objects;

/**
 * The specification for part 2 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it with:   run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Eleven tests, and between them they lean on all five principles.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- the two formats produce exactly the right text --------------------------------
        check("csv puts the title on line one, then each row", () ->
            expectEquals("""
                            Sales
                            a
                            b""",
                new CsvFormat().format(new Report("Sales", List.of("a", "b")))));

        check("csv of an empty report is just the title", () ->
            expectEquals("Empty",
                new CsvFormat().format(new Report("Empty", List.of()))));

        check("csv keeps three rows of real text, in order", () ->
            expectEquals("""
                            Q3
                            north,12
                            south,7
                            east,0""",
                new CsvFormat().format(new Report("Q3", List.of("north,12", "south,7", "east,0")))));

        check("json has a title and a rows array", () ->
            expectEquals("""
                            {"title":"Sales","rows":["a","b"]}""",
                new JsonFormat().format(new Report("Sales", List.of("a", "b")))));

        check("json of an empty report has an empty array", () ->
            expectEquals("""
                            {"title":"Empty","rows":[]}""",
                new JsonFormat().format(new Report("Empty", List.of()))));

        check("json quotes one row, and three rows, with no stray comma", () -> {
            expectEquals("""
                            {"title":"One","rows":["solo"]}""",
                new JsonFormat().format(new Report("One", List.of("solo"))));
            expectEquals("""
                            {"title":"Q3","rows":["north","south","east"]}""",
                new JsonFormat().format(new Report("Q3", List.of("north", "south", "east"))));
        });

        // --- DIP: the service uses whatever format it was given, nothing else --------------
        check("the service returns the format's output unchanged", () ->
            expectEquals("""
                            Sales
                            a
                            b""",
                new ReportService(new CsvFormat()).export(new Report("Sales", List.of("a", "b")))));

        check("the service calls the injected format once, with the report it was handed", () -> {
            Report r = new Report("Sales", List.of("a", "b"));
            int[] calls = {0};
            ReportFormat recorder = report -> { calls[0]++; expectEquals(r, report); return "recorded"; };
            expectEquals("recorded", new ReportService(recorder).export(r));
            expectEquals(1, calls[0]);
        });

        // --- SRP: validation lives in the service, not the formatter -----------------------
        check("the service rejects a blank title", () ->
            expectThrows(IllegalArgumentException.class, () ->
                new ReportService(new CsvFormat()).export(new Report("   ", List.of("a")))));

        // --- OCP + DIP: a brand new format works with the UNCHANGED service -----------------
        check("the service accepts a new format it has never seen", () -> {
            ReportFormat plain = report -> "plain:" + report.title();   // a format defined right here
            expectEquals("plain:Sales",
                new ReportService(plain).export(new Report("Sales", List.of("a"))));
        });

        // --- LSP + ISP: every format is substitutable through the one interface ------------
        check("both formats go through the same service and keep their own shape", () -> {
            Report r = new Report("Q", List.of("x"));
            expectEquals("Q\nx", new ReportService(new CsvFormat()).export(r));
            expectEquals("{\"title\":\"Q\",\"rows\":[\"x\"]}", new ReportService(new JsonFormat()).export(r));
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. The five principles are doing real work now.");
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
