package wrappers;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;

/**
 * The specification for part 2 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Fourteen tests. The first one documents a bug on purpose; the rest prove you fixed it
 * by wrapping rather than extending, and that LinkedHashMap can be an LRU cache.
 * Make every test green.
 *
 * A note for whoever teaches this next: the 6 asserted in the first test is HashSet.addAll
 * looping over add, which is an implementation detail rather than a promise. It is green on
 * JDK 25. If a future JDK stops writing addAll that way, this is the test that will turn red,
 * and it will not be the student's fault. Nothing else here depends on JDK internals.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- the bug, written down (Item 18). This one is green before you start. ---------
        check("InstrumentedHashSet double counts, because HashSet.addAll calls add", () -> {
            InstrumentedHashSet<String> broken = new InstrumentedHashSet<>();
            broken.addAll(List.of("a", "b", "c"));
            expectEquals(6, broken.getAddCount());          // three, counted twice
            broken.add("d");
            expectEquals(7, broken.getAddCount());
            expectEquals(4, broken.size());
        });

        // --- the fix: forward, do not inherit --------------------------------------------
        check("InstrumentedSet counts each element once, whatever the batch size", () -> {
            InstrumentedSet<String> counted = new InstrumentedSet<>(new HashSet<>());
            counted.addAll(List.of("a", "b", "c"));
            expectEquals(3, counted.getAddCount());

            counted.addAll(List.of("d", "e"));              // a different size, on purpose
            expectEquals(5, counted.getAddCount());

            counted.add("f");
            expectEquals(6, counted.getAddCount());
            expectEquals(6, counted.size());
        });

        check("a duplicate add is still an attempt, even though the set does not grow", () -> {
            InstrumentedSet<String> counted = new InstrumentedSet<>(new HashSet<>());
            counted.add("a");
            expectTrue("adding a fresh element returns true", counted.add("b"));
            expectTrue("adding a duplicate returns false", !counted.add("a"));
            expectEquals(3, counted.getAddCount());
            expectEquals(2, counted.size());

            counted.addAll(List.of("a", "b"));              // both already present
            expectEquals(5, counted.getAddCount());
            expectEquals(2, counted.size());
        });

        check("the wrapper works over ANY Set, which a subclass of HashSet never could", () -> {
            InstrumentedSet<String> sorted = new InstrumentedSet<>(new TreeSet<>());
            sorted.addAll(List.of("pear", "apple", "fig"));
            expectEquals(List.of("apple", "fig", "pear"), drain(sorted));
            expectEquals(3, sorted.getAddCount());

            InstrumentedSet<String> insertionOrder = new InstrumentedSet<>(new LinkedHashSet<>());
            insertionOrder.addAll(List.of("pear", "apple", "fig"));
            expectEquals(List.of("pear", "apple", "fig"), drain(insertionOrder));
            expectEquals(3, insertionOrder.getAddCount());
        });

        // --- the forwarding you finished --------------------------------------------------
        check("containsAll answers for a subset and for one missing element", () -> {
            Set<String> forwarding = new ForwardingSet<>(new HashSet<>(List.of("a", "b", "c")));
            expectTrue("a,b is a subset", forwarding.containsAll(List.of("a", "b")));
            expectTrue("the empty collection is always a subset", forwarding.containsAll(List.of()));
            expectTrue("a,z is not", !forwarding.containsAll(List.of("a", "z")));
            expectTrue("z alone is not", !forwarding.containsAll(List.of("z")));
        });

        check("retainAll keeps the intersection, exactly like the wrapped set would", () -> {
            Set<String> forwarding = new ForwardingSet<>(new HashSet<>(List.of("a", "b", "c", "d")));
            Set<String> control = new HashSet<>(List.of("a", "b", "c", "d"));
            List<String> keep = List.of("b", "d", "z");

            expectEquals(control.retainAll(keep), forwarding.retainAll(keep));
            expectEquals(sortedText(control), sortedText(forwarding));
            expectEquals(List.of("b", "d"), sortedText(forwarding));

            expectEquals(control.retainAll(keep), forwarding.retainAll(keep));   // now a no-op, false

            // A second argument of a different shape, so forwarding the collection you were
            // GIVEN is pinned, not just calling the right method with something plausible.
            List<String> narrower = List.of("d");
            expectEquals(control.retainAll(narrower), forwarding.retainAll(narrower));
            expectEquals(List.of("d"), sortedText(forwarding));
            expectEquals(sortedText(control), sortedText(forwarding));
        });

        check("removeAll drops the intersection, exactly like the wrapped set would", () -> {
            Set<String> forwarding = new ForwardingSet<>(new HashSet<>(List.of("a", "b", "c", "d")));
            Set<String> control = new HashSet<>(List.of("a", "b", "c", "d"));
            List<String> drop = List.of("a", "c", "z");

            expectEquals(control.removeAll(drop), forwarding.removeAll(drop));
            expectEquals(sortedText(control), sortedText(forwarding));
            expectEquals(List.of("b", "d"), sortedText(forwarding));

            // Same again with a different collection: a wrapper that ignores its argument
            // and passes a remembered one gets this far and then disagrees with the control.
            List<String> justB = List.of("b");
            expectEquals(control.removeAll(justB), forwarding.removeAll(justB));
            expectEquals(List.of("d"), sortedText(forwarding));
            expectEquals(sortedText(control), sortedText(forwarding));

            expectEquals(control.removeAll(List.of("q")), forwarding.removeAll(List.of("q")));
        });

        check("addAll through the wrapper really reaches the wrapped set", () -> {
            Set<String> inner = new HashSet<>();
            Set<String> forwarding = new ForwardingSet<>(inner);
            expectTrue("adding two new elements changed the set", forwarding.addAll(List.of("a", "b")));
            expectEquals(2, inner.size());
            expectEquals(List.of("a", "b"), sortedText(inner));
            expectTrue("adding the same two again changed nothing", !forwarding.addAll(List.of("a", "b")));
        });

        check("a ForwardingSet is equal to any Set with the same elements, and hashes alike", () -> {
            Set<String> forwarding = new ForwardingSet<>(new HashSet<>(List.of("a", "b")));
            Set<String> plain = new HashSet<>(List.of("a", "b"));

            expectTrue("wrapper equals a plain HashSet with the same elements", forwarding.equals(plain));
            expectTrue("and the plain HashSet agrees, which is what symmetry means", plain.equals(forwarding));
            expectEquals(plain.hashCode(), forwarding.hashCode());
            expectEquals(Set.of("a", "b").hashCode(), forwarding.hashCode());

            Set<String> other = new ForwardingSet<>(new TreeSet<>(List.of("a", "b")));
            expectTrue("two wrappers over equal sets are equal", forwarding.equals(other));
            expectEquals(forwarding.hashCode(), other.hashCode());

            expectTrue("a different set is not equal", !forwarding.equals(new HashSet<>(List.of("a", "z"))));
            expectTrue("a bigger set is not equal", !forwarding.equals(new HashSet<>(List.of("a", "b", "c"))));
        });

        // --- LinkedHashMap in access order ------------------------------------------------
        check("a read counts as a use: get(a) then put(c) evicts b, not a", () -> {
            LruCache<String, Integer> cache = new LruCache<>(2);
            cache.put("a", 1);
            cache.put("b", 2);
            expectEquals(1, (int) cache.get("a"));      // a is now the freshest
            cache.put("c", 3);

            expectEquals(2, cache.size());
            expectTrue("a survived because we read it", cache.containsKey("a"));
            expectTrue("b was the least recently used", !cache.containsKey("b"));
            expectTrue("c is in", cache.containsKey("c"));
        });

        check("without the read, the first key is the one that goes", () -> {
            LruCache<String, Integer> cache = new LruCache<>(2);
            cache.put("a", 1);
            cache.put("b", 2);
            cache.put("c", 3);

            expectEquals(2, cache.size());
            expectTrue("a went", !cache.containsKey("a"));
            expectEquals(List.of("b", "c"), new ArrayList<>(cache.keySet()));
        });

        check("the cache never grows past its capacity, at two different capacities", () -> {
            LruCache<Integer, Integer> three = new LruCache<>(3);
            for (int i = 0; i < 50; i++) {
                three.put(i, i * i);
                expectTrue("size " + three.size() + " must never exceed 3", three.size() <= 3);
            }
            expectEquals(3, three.size());
            expectEquals(List.of(47, 48, 49), new ArrayList<>(three.keySet()));

            LruCache<Integer, Integer> one = new LruCache<>(1);
            for (int i = 0; i < 20; i++) one.put(i, i);
            expectEquals(1, one.size());
            expectEquals(List.of(19), new ArrayList<>(one.keySet()));
        });

        check("re-putting a key refreshes it, so the OTHER key ages out", () -> {
            LruCache<String, Integer> cache = new LruCache<>(2);
            cache.put("a", 1);
            cache.put("b", 2);
            cache.put("a", 11);                         // a written again, so a is freshest
            cache.put("c", 3);

            expectTrue("a survived and kept its new value", cache.containsKey("a"));
            expectEquals(11, (int) cache.get("a"));
            expectTrue("b aged out", !cache.containsKey("b"));
            expectEquals(2, cache.size());
        });

        check("a miss returns null and evicts nobody", () -> {
            LruCache<String, Integer> cache = new LruCache<>(2);
            cache.put("a", 1);
            cache.put("b", 2);

            expectEquals(null, cache.get("nothing-like-this"));
            expectEquals(2, cache.size());
            expectTrue("a is still there", cache.containsKey("a"));
            expectTrue("b is still there", cache.containsKey("b"));
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. You wrapped the set instead of extending it, and the count is honest.");
    }

    // --- fixtures -------------------------------------------------------------
    static List<String> drain(Iterable<String> items) {
        List<String> out = new ArrayList<>();
        for (String s : items) out.add(s);
        return out;
    }

    static List<String> sortedText(Iterable<String> items) {
        List<String> out = drain(items);
        out.sort(null);
        return out;
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectTrue(String what, boolean got) {
        if (!got) throw new AssertionError(what);
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
