package state;

import java.net.CookieManager;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * The specification for part 2 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Ten tests: a filter, a listener, a session, and one counter under fifty threads.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    /** Held in a field on purpose. java.util.logging keeps its loggers weakly, so a level set on a
     *  logger nobody holds is collected again before Tomcat ever logs through it. */
    static final Logger HUSH = Logger.getLogger("org.apache.catalina.loader.WebappClassLoaderBase");

    static Server server;
    static int port = 0;

    /** Keeps JSESSIONID, so it looks like one browser coming back. */
    static final HttpClient BROWSER = HttpClient.newBuilder().cookieHandler(new CookieManager()).build();
    /** Drops every cookie, so it is a new stranger on every request. */
    static final HttpClient STRANGER = HttpClient.newHttpClient();
    /** Never follows a 302, so we can look at the redirect itself. */
    static final HttpClient NO_FOLLOW = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NEVER).build();

    public static void main(String[] args) {

        Logger.getLogger("").setLevel(Level.WARNING);   // Tomcat narrates itself at INFO; hush it
        HUSH.setLevel(Level.SEVERE);                   // and its leak detector, which talks at WARNING

        check("the application is live: the filter, the listener and all eight mappings answer", () -> {
            server = new Server(0);
            server.start();
            port = server.port();
            if (port <= 0) throw new AssertionError("the connector reported port " + port);

            // A connector reports a port even when the context behind it failed to start, and then
            // every path below comes back as Tomcat's own HTML 404. So ask the application itself.
            // Every mapping, once: the only 404 that counts as an answer is the one your "/" servlet
            // writes. And every reply must carry the header the filter sets on the way in.
            for (String path : List.of("/visit", "/hits", "/info", "/new", "/old", "/alias", "/admin/x", "/")) {
                HttpResponse<String> r = send(NO_FOLLOW, HttpRequest.newBuilder(uri(path)).GET().build());
                if (r.statusCode() == 404 && !r.body().startsWith("no such path:")) {
                    throw new AssertionError("GET " + path + " was answered by the container, not by your code, so the"
                            + " context never started: " + r.statusCode() + " [" + oneLine(r.body()) + "]");
                }
                if (header(r, "X-Request-Id").isBlank()) {
                    throw new AssertionError("GET " + path + " came back with no X-Request-Id, so the filter is not in the chain");
                }
            }
            // and the listener published into application scope before any of that arrived
            expectEquals("byts-bank", get(STRANGER, "/info").body().split(" ")[0]);
        });

        // --- the filter sees every request, including the ones nobody mapped ------------------
        check("every request leaves exactly one 'METHOD /path -> status' line, misses included", () -> {
            server.log().clear();
            get(STRANGER, "/visit");
            get(STRANGER, "/info");
            get(STRANGER, "/nothing");
            post(STRANGER, "/new");
            expectEquals(List.of("GET /visit -> 200",
                                 "GET /info -> 200",
                                 "GET /nothing -> 404",
                                 "POST /new -> 405"),
                    server.log().lines());
            expectEquals(4, server.log().millis().size());
            for (long ms : server.log().millis()) {
                if (ms < 0 || ms > 60_000) throw new AssertionError("a request was logged as taking " + ms + " ms");
            }
        });

        check("every response carries a fresh X-Request-Id, set before the chain ran", () -> {
            String a = header(get(STRANGER, "/visit"), "X-Request-Id");
            String b = header(get(STRANGER, "/info"), "X-Request-Id");     // this one flushed: too late to add headers
            String c = header(get(STRANGER, "/nothing"), "X-Request-Id");
            for (String id : List.of(a, b, c)) {
                if (id.isBlank()) throw new AssertionError("a response came back with no X-Request-Id at all");
            }
            if (a.equals(b) || b.equals(c)) throw new AssertionError("two requests shared the id [" + b + "], so it is not per request");
        });

        check("a filter can short circuit: /admin without a token never reaches the servlet", () -> {
            server.log().clear();
            HttpResponse<String> blocked = get(STRANGER, "/admin/x");
            expectEquals(401, blocked.statusCode());
            if (blocked.body().startsWith("admin ok")) throw new AssertionError("the servlet answered, so chain.doFilter was called anyway");
            expectEquals(List.of("GET /admin/x -> 401"), server.log().lines());

            expectEquals(401, get(STRANGER, "/admin/reports/2026").statusCode());

            HttpResponse<String> allowed = send(STRANGER, HttpRequest.newBuilder(uri("/admin/x")).header("X-Token", "s3cr3t").GET().build());
            expectEquals(200, allowed.statusCode());
            expectEquals("admin ok /x", allowed.body());
        });

        // --- application scope, published by a listener before anyone asked ------------------
        check("GET /info reports the name and start time the listener published", () -> {
            HttpResponse<String> r = get(STRANGER, "/info");
            expectEquals(200, r.statusCode());
            String[] parts = r.body().split(" ");
            expectEquals(2, parts.length);
            expectEquals("byts-bank", parts[0]);
            Instant started = Instant.parse(parts[1]);
            if (started.isAfter(Instant.now().plusSeconds(5))) throw new AssertionError("startedAt is in the future: " + started);
            if (started.isBefore(Instant.now().minusSeconds(3600))) throw new AssertionError("startedAt is an hour old: " + started);
        });

        // --- session scope ------------------------------------------------------------------
        check("a client that keeps its cookie keeps its count: visit 1, 2, 3", () -> {
            expectEquals("visit 1", get(BROWSER, "/visit").body());
            expectEquals("visit 2", get(BROWSER, "/visit").body());
            expectEquals("visit 3", get(BROWSER, "/visit").body());
        });

        check("a client that drops cookies is a stranger every time: visit 1, three times over", () -> {
            expectEquals("visit 1", get(STRANGER, "/visit").body());
            expectEquals("visit 1", get(STRANGER, "/visit").body());
            expectEquals("visit 1", get(STRANGER, "/visit").body());
            expectEquals("visit 4", get(BROWSER, "/visit").body());     // and the browser's own count is untouched
        });

        // --- one servlet instance, fifty threads --------------------------------------------
        check("50 threads x 20 requests to /hits hand out 1 to 1000 exactly, three rounds, each one timed", () -> {
            long timed = 0;
            for (int round = 1; round <= 3; round++) {
                expectEquals("hits 0", get(STRANGER, "/hits?reset=true").body());
                server.log().clear();
                Set<Integer> seen = hammer(50, 1000);
                timed += server.log().millis().stream().filter(ms -> ms >= 1).count();
                if (seen.size() != 1000) {
                    throw new AssertionError("round " + round + ": 1000 requests produced only " + seen.size()
                            + " different counts, so increments were lost (highest was " + new TreeSet<>(seen).last() + ")");
                }
                expectEquals(1, new TreeSet<>(seen).first().intValue());
                expectEquals(1000, new TreeSet<>(seen).last().intValue());
            }
            // Three thousand requests over fifty threads, and not one of them took a whole
            // millisecond? Then the second argument to log.add is not the elapsed time.
            if (timed == 0) {
                throw new AssertionError("every one of 3000 contended requests was logged as 0 ms:"
                        + " log.add's second argument has to be how long the chain really took");
            }
        });

        // --- forward versus redirect --------------------------------------------------------
        check("GET /old is a 302 with a Location: the client is told to ask again", () -> {
            server.log().clear();
            HttpResponse<String> r = send(NO_FOLLOW, HttpRequest.newBuilder(uri("/old")).GET().build());
            expectEquals(302, r.statusCode());
            String location = r.headers().firstValue("Location").orElse("");
            if (!location.endsWith("/new")) throw new AssertionError("expected a Location ending /new but got [" + location + "]");
            expectEquals("", r.body());
            expectEquals(List.of("GET /old -> 302"), server.log().lines());
        });

        check("GET /alias forwards inside the container: one request, one log line, a new URI", () -> {
            server.log().clear();
            HttpResponse<String> r = get(STRANGER, "/alias");
            expectEquals(200, r.statusCode());
            expectEquals("new uri=/new from=/alias disp=FORWARD", r.body());
            expectEquals(List.of("GET /alias -> 200"), server.log().lines());
        });

        try {
            if (server != null) server.stop();
        } catch (RuntimeException teardown) {
            System.out.println("(the server would not stop cleanly: " + teardown + ")");
        }

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. Scopes, a filter chain and a counter that survives fifty threads.");
    }

    // --- talking to the server ------------------------------------------------------
    static URI uri(String path) {
        if (port == 0) throw new AssertionError("the server is not up, so this request cannot be made");
        return URI.create("http://localhost:" + port + path);
    }

    static HttpResponse<String> send(HttpClient client, HttpRequest req) throws Exception {
        return client.send(req, HttpResponse.BodyHandlers.ofString());
    }

    static HttpResponse<String> get(HttpClient client, String path) throws Exception {
        return send(client, HttpRequest.newBuilder(uri(path)).GET().build());
    }

    static HttpResponse<String> post(HttpClient client, String path) throws Exception {
        return send(client, HttpRequest.newBuilder(uri(path)).POST(HttpRequest.BodyPublishers.ofString("")).build());
    }

    static String header(HttpResponse<?> r, String name) {
        return r.headers().firstValue(name).orElse("");
    }

    /** Tomcat's 404 page is several lines of HTML; squash it so a failure message stays readable. */
    static String oneLine(String body) {
        String s = body.replaceAll("\\s+", " ").strip();
        return s.length() > 90 ? s.substring(0, 90) + "..." : s;
    }

    /** Fires `total` requests at /hits over `threads` threads and returns every count it was handed. */
    static Set<Integer> hammer(int threads, int total) throws Exception {
        ExecutorService pool = Executors.newFixedThreadPool(threads);
        List<Callable<Integer>> jobs = new ArrayList<>();
        for (int i = 0; i < total; i++) {
            jobs.add(() -> {
                String body = get(STRANGER, "/hits").body();
                if (!body.startsWith("hits ")) throw new AssertionError("expected a body like 'hits 7' but got [" + body + "]");
                return Integer.parseInt(body.substring("hits ".length()).trim());
            });
        }
        Set<Integer> seen = new TreeSet<>();
        try {
            for (Future<Integer> f : pool.invokeAll(jobs)) seen.add(f.get());
        } finally {
            pool.shutdownNow();
        }
        return seen;
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
