package finale;

import java.io.PrintWriter;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.logging.Logger;

import javax.sql.DataSource;

import org.h2.jdbcx.JdbcDataSource;

/**
 * The specification for the finale. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * The first four tests run TWICE, once against the HashMap repository and once
 * against yours, from the same loop. That loop is the argument of the whole day.
 * Make every test green.
 */
public class RunTests {

    static final String URL = "jdbc:h2:mem:finale;DB_CLOSE_DELAY=-1";

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL(URL);
        JdbcAccountRepository jdbc = new JdbcAccountRepository(dataSource);

        check("the JDBC repository builds its own table when asked, not when constructed", () -> {
            Spy spy = new Spy(dataSource);
            JdbcAccountRepository built = new JdbcAccountRepository(spy);
            if (spy.connections != 0) {
                throw new AssertionError("the constructor asked for " + spy.connections + " connection(s): a repository is built at "
                        + "startup, when the database may still be waking up, so it must do no I/O until somebody calls a method");
            }
            built.createSchema();
            if (spy.connections == 0) throw new AssertionError("createSchema() never asked the DataSource for a connection");
            jdbc.createSchema();
            try (Connection c = dataSource.getConnection();
                 ResultSet rs = c.getMetaData().getTables(null, null, "ACCOUNT", new String[]{"TABLE"})) {
                if (!rs.next()) throw new AssertionError("createSchema() left no ACCOUNT table behind");
            }
        });

        // --- the same contract, both implementations ---------------------------
        contract("in memory", new InMemoryAccountRepository());
        contract("jdbc", jdbc);

        // --- and now the things only the JDBC one can get wrong ------------------
        check("[jdbc] generated ids climb in insertion order across two saveAll calls", () -> {
            jdbc.deleteAll();
            List<Account> first = jdbc.saveAll(List.of(Account.of("a", 1), Account.of("b", 2)));
            List<Account> second = jdbc.saveAll(List.of(Account.of("c", 3), Account.of("d", 4)));
            List<Account> all = new ArrayList<>(first);
            all.addAll(second);
            long previous = Long.MIN_VALUE;
            for (Account a : all) {
                if (a.id() == null || a.id() <= previous) {
                    throw new AssertionError("ids should climb, but got " + all.stream().map(Account::id).toList());
                }
                previous = a.id();
            }
            // and every id has to point at its own row, not just look plausible
            expectEquals("b", jdbc.findById(first.get(1).id()).orElseThrow().owner());
            expectEquals("c", jdbc.findById(second.get(0).id()).orElseThrow().owner());
            expectEquals(4, jdbc.count());
        });

        check("[jdbc] one illegal row in the middle of a batch leaves the table exactly as it was", () -> {
            jdbc.deleteAll();
            jdbc.save(Account.of("keep me", 10));
            expectEquals(1, jdbc.count());
            expectThrows(RepositoryException.class, () -> jdbc.saveAll(List.of(
                    Account.of("first", 1),
                    Account.of("illegal", -1),
                    Account.of("third", 3))));
            expectEquals(1, jdbc.count());
            expectEquals("keep me", jdbc.findAll().get(0).owner());

            // a longer batch, failing at the very end, has to roll back just the same
            List<Account> big = new ArrayList<>();
            for (int i = 0; i < 200; i++) big.add(Account.of("row-" + i, i));
            big.add(Account.of("illegal", -5));
            expectThrows(RepositoryException.class, () -> jdbc.saveAll(big));
            expectEquals(1, jdbc.count());
        });

        check("[jdbc] the RepositoryException keeps the cause, and a bad batch row arrives as a BatchUpdateException", () -> {
            jdbc.deleteAll();
            RepositoryException e = expectThrows(RepositoryException.class, () -> jdbc.saveAll(List.of(
                    Account.of("fine", 1),
                    Account.of("illegal", -1))));
            Throwable cause = e.getCause();
            if (!(cause instanceof BatchUpdateException batch)) {
                throw new AssertionError("expected the cause to be a BatchUpdateException but got " + cause);
            }
            SQLException inner = batch.getNextException();
            if (!(inner instanceof SQLIntegrityConstraintViolationException)) {
                throw new AssertionError("expected getNextException() to be the integrity violation but got " + inner);
            }
            expectEquals("23", String.valueOf(inner.getSQLState()).substring(0, 2));
            if (batch.getSQLState() != null) {
                expectEquals("23", batch.getSQLState().substring(0, 2));
            }
        });

        check("[jdbc] a repository over an unusable DataSource builds fine and fails at the query", () -> {
            JdbcDataSource broken = new JdbcDataSource();
            broken.setURL("jdbc:h2:mem:not-a-database-" + System.nanoTime() + ";IFEXISTS=TRUE");
            // The constructor does no I/O, so this line must not throw.
            JdbcAccountRepository doomed = new JdbcAccountRepository(broken);
            expectThrows(RepositoryException.class, doomed::findAll);
            expectThrows(RepositoryException.class, doomed::count);
            expectThrows(RepositoryException.class, () -> doomed.findById(1));
            expectThrows(RepositoryException.class, () -> doomed.save(Account.of("nobody", 1)));
        });

        check("[jdbc] count() asks the database for the number instead of dragging every row home", () -> {
            Spy spy = new Spy(dataSource);
            JdbcAccountRepository watched = new JdbcAccountRepository(spy);
            watched.deleteAll();
            List<Account> many = new ArrayList<>();
            for (int i = 0; i < 300; i++) many.add(Account.of("row-" + i, i));
            watched.saveAll(many);

            spy.sql.clear();
            expectEquals(300, watched.count());
            if (spy.sql.isEmpty()) throw new AssertionError("count() ran no SQL at all");
            for (String ran : spy.sql) {
                if (!ran.toLowerCase().contains("count(")) {
                    throw new AssertionError("count() ran [" + ran + "]: let the database do the counting. "
                            + "Pulling 300 rows across the wire to call size() on them is this afternoon's N+1 in miniature");
                }
            }
        });

        check("[jdbc] 50 queries later there is still exactly one open session: yours", () -> {
            jdbc.deleteAll();
            jdbc.save(Account.of("ana", 10_000));
            for (int i = 0; i < 50; i++) {
                jdbc.findAll();
                jdbc.count();
                jdbc.findById(1);
            }
            try (Connection c = dataSource.getConnection();
                 Statement s = c.createStatement();
                 ResultSet rs = s.executeQuery("SELECT count(*) FROM INFORMATION_SCHEMA.SESSIONS")) {
                rs.next();
                long sessions = rs.getLong(1);
                if (sessions != 1) {
                    throw new AssertionError("expected 1 open session (this one) but found " + sessions
                            + ": a borrowed connection was never closed");
                }
            }
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. One interface, two implementations, and a service that never knew which.");
    }

    /**
     * The contract every AccountRepository has to honour, whatever is underneath it.
     * Run once per implementation. Liskov, as an executable idea.
     */
    static void contract(String who, AccountRepository repo) {

        check("[" + who + "] save fills in an id and hands back a copy, leaving your account alone", () -> {
            repo.deleteAll();
            Account unsaved = Account.of("ana", 10_000);
            Account saved = repo.save(unsaved);
            expectEquals(null, unsaved.id());
            if (saved.id() == null) throw new AssertionError("save must return an account carrying its new id");
            expectEquals("ana", saved.owner());
            expectEquals(10_000, saved.balanceCents());

            Account second = repo.save(Account.of("bo", 5));
            expectEquals("bo", second.owner());
            expectEquals(5, second.balanceCents());
            if (second.id().equals(saved.id())) throw new AssertionError("two saved accounts share the id " + saved.id());
            expectEquals(2, repo.count());
        });

        check("[" + who + "] findById gives back what you saved, and Optional.empty for an id nobody has", () -> {
            repo.deleteAll();
            Account ana = repo.save(Account.of("ana", 10_000));
            Account bo = repo.save(Account.of("bo", 5_000));
            expectEquals(ana, repo.findById(ana.id()).orElseThrow());
            expectEquals(bo, repo.findById(bo.id()).orElseThrow());
            expectEquals(Optional.empty(), repo.findById(999_999));
            expectEquals(Optional.empty(), repo.findById(ana.id() + bo.id() + 1_000));
            expectEquals(2, repo.count());
            repo.deleteAll();
            expectEquals(0, repo.count());
            expectEquals(List.of(), repo.findAll());
            expectEquals(Optional.empty(), repo.findById(ana.id()));
        });

        check("[" + who + "] saveAll of 1000 accounts gives 1000 distinct ids, and the data survives", () -> {
            repo.deleteAll();
            List<Account> batch = new ArrayList<>();
            for (int i = 0; i < 1_000; i++) batch.add(Account.of("owner-" + i, i));
            List<Account> saved = repo.saveAll(batch);
            expectEquals(1_000, saved.size());
            expectEquals(1_000, saved.stream().map(Account::id).filter(Objects::nonNull).distinct().count());
            expectEquals(1_000, repo.count());
            expectEquals("owner-0", saved.get(0).owner());
            expectEquals("owner-999", saved.get(999).owner());
            expectEquals(999, saved.get(999).balanceCents());
            expectEquals(499_500, repo.findAll().stream().mapToLong(Account::balanceCents).sum());
            expectEquals("owner-500", repo.findById(saved.get(500).id()).orElseThrow().owner());

            // a much smaller batch, so a hard-coded 1000 gets nowhere
            repo.deleteAll();
            List<Account> three = repo.saveAll(List.of(Account.of("x", 1), Account.of("y", 2), Account.of("z", 3)));
            expectEquals(3, three.size());
            expectEquals(3, repo.count());
            expectEquals(6, repo.findAll().stream().mapToLong(Account::balanceCents).sum());
            expectEquals(List.of(), repo.saveAll(List.of()));
        });

        // The dispatch in AccountService is given, so this cannot fail for a polymorphism
        // mistake: it checks that the service's arithmetic is right over THIS repository,
        // and the fact that it runs twice unchanged is the day's argument, not a test.
        check("[" + who + "] the service totals and ranks correctly over this repository", () -> {
            repo.deleteAll();
            AccountService service = new AccountService(repo);
            expectEquals(0, service.totalBalance());
            expectEquals(Optional.empty(), service.richest());

            repo.saveAll(List.of(Account.of("ana", 10_000), Account.of("bo", 5_000), Account.of("O'Brien", 700)));
            expectEquals(15_700, service.totalBalance());
            expectEquals("ana", service.richest().orElseThrow().owner());

            repo.deleteAll();
            repo.save(Account.of("solo", 42));
            expectEquals(42, service.totalBalance());
            expectEquals("solo", service.richest().orElseThrow().owner());
        });
    }

    /**
     * A DataSource that writes down what the repository did with it: how many connections
     * it borrowed, and what SQL it sent. Nothing exotic, just a wrapper, which is the same
     * trick a pool plays on you.
     */
    static final class Spy implements DataSource {

        private final DataSource real;
        int connections = 0;
        final List<String> sql = new ArrayList<>();

        Spy(DataSource real) { this.real = real; }

        @Override public Connection getConnection() throws SQLException { connections++; return watch(real.getConnection()); }
        @Override public Connection getConnection(String u, String p) throws SQLException { connections++; return watch(real.getConnection(u, p)); }
        @Override public PrintWriter getLogWriter() throws SQLException { return real.getLogWriter(); }
        @Override public void setLogWriter(PrintWriter out) throws SQLException { real.setLogWriter(out); }
        @Override public void setLoginTimeout(int seconds) throws SQLException { real.setLoginTimeout(seconds); }
        @Override public int getLoginTimeout() throws SQLException { return real.getLoginTimeout(); }
        @Override public Logger getParentLogger() { return Logger.getGlobal(); }
        @Override public <T> T unwrap(Class<T> iface) throws SQLException { return real.unwrap(iface); }
        @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return real.isWrapperFor(iface); }

        private Connection watch(Connection c) {
            return (Connection) Proxy.newProxyInstance(Spy.class.getClassLoader(), new Class<?>[]{Connection.class},
                    (proxy, method, args) -> {
                        note(args);
                        Object out = call(method, c, args);
                        return (out instanceof Statement st && !(out instanceof PreparedStatement)) ? watch(st) : out;
                    });
        }

        private Statement watch(Statement st) {
            return (Statement) Proxy.newProxyInstance(Spy.class.getClassLoader(), new Class<?>[]{Statement.class},
                    (proxy, method, args) -> { note(args); return call(method, st, args); });
        }

        private void note(Object[] args) {
            if (args != null && args.length > 0 && args[0] instanceof String s) sql.add(s);
        }

        private static Object call(Method m, Object target, Object[] args) throws Throwable {
            try { return m.invoke(target, args); }
            catch (InvocationTargetException e) { throw e.getCause(); }
        }
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static <T extends Throwable> T expectThrows(Class<T> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return expected.cast(t);
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
