package keys;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.function.Supplier;

/**
 * The specification for part 1 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Seventeen tests. Between them they pin the equals, hashCode and compareTo contracts,
 * and the two places where behaviour arrives as a parameter.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- parsing: three numbers in, one immutable value out ---------------------------
        check("parse reads major, minor and patch, and toString round-trips", () -> {
            Version a = Version.parse("1.10.0");
            expectEquals(1, a.major());
            expectEquals(10, a.minor());
            expectEquals(0, a.patch());
            expectEquals("1.10.0", a.toString());

            Version b = Version.parse("0.0.0");
            expectEquals(0, b.major());
            expectEquals(0, b.minor());
            expectEquals(0, b.patch());
            expectEquals("0.0.0", b.toString());

            Version c = Version.parse("12.7.301");
            expectEquals(12, c.major());
            expectEquals(7, c.minor());
            expectEquals(301, c.patch());
            expectEquals("12.7.301", c.toString());
        });

        check("parse rejects every shape that is not three numbers", () -> {
            for (String bad : new String[] { "1.2", "1.x.3", "", "1.2.3.4", "1..3", "1.2.", "x",
                                             "\t", " . . ", " 1.2.3", "1.2.3 ", "-1.2.3" }) {
                expectThrows(IllegalArgumentException.class, () -> Version.parse(bad));
            }
        });

        check("parse rejects null, which is the half people forget", () -> {
            expectThrows(IllegalArgumentException.class, () -> Version.parse(null));
            expectThrows(IllegalArgumentException.class, () -> Version.parse("   "));
        });

        // --- Items 10 and 11: equals and hashCode, together -------------------------------
        check("two separately parsed copies of the same text are equal and hash alike", () -> {
            Version a = Version.parse("1.2.3");
            Version b = Version.parse("1.2.3");
            expectTrue("1.2.3 should equal 1.2.3", a.equals(b));
            expectTrue("equals must be symmetric", b.equals(a));
            expectEquals(a.hashCode(), b.hashCode());
        });

        check("hashCode spreads different versions across different buckets", () -> {
            Set<Integer> hashes = new HashSet<>();
            for (int major = 0; major < 10; major++) {
                for (int minor = 0; minor < 20; minor++) {
                    hashes.add(Version.parse(major + "." + minor + ".0").hashCode());
                }
            }
            expectTrue("200 different versions produced only " + hashes.size()
                       + " different hash codes. `return 42;` is legal and it is also useless: "
                       + "every key lands in one bucket and the map degrades to a list (Item 11)",
                hashes.size() > 150);
        });

        check("versions that differ in any one field are NOT equal", () -> {
            Version base = Version.parse("1.2.3");
            for (String other : new String[] { "2.2.3", "1.3.3", "1.2.4", "0.2.3" }) {
                expectTrue(other + " should not equal 1.2.3", !base.equals(Version.parse(other)));
            }
            expectTrue("a Version never equals null", !base.equals(null));
            expectTrue("a Version never equals a String", !base.equals("1.2.3"));
        });

        check("a HashSet uses hashCode then equals, so equal copies collapse", () -> {
            Set<Version> set = new HashSet<>();
            set.add(Version.parse("1.2.3"));
            set.add(Version.parse("1.2.3"));
            expectEquals(1, set.size());

            set.add(Version.parse("2.0.0"));
            set.add(Version.parse("1.2.4"));
            expectEquals(3, set.size());
            expectTrue("a fresh equal copy must be found", set.contains(Version.parse("2.0.0")));
            expectTrue("a version never added must not be found", !set.contains(Version.parse("9.9.9")));
        });

        // --- Item 14: compareTo, numeric and consistent with equals -----------------------
        check("compareTo orders numerically, not like text", () -> {
            expectTrue("1.9.0 must come before 1.10.0", Version.parse("1.9.0").compareTo(Version.parse("1.10.0")) < 0);
            expectTrue("1.10.0 must come before 2.0.0", Version.parse("1.10.0").compareTo(Version.parse("2.0.0")) < 0);
            expectTrue("1.2.3 must come before 1.2.10", Version.parse("1.2.3").compareTo(Version.parse("1.2.10")) < 0);
            expectTrue("2.0.0 must come after 1.10.0", Version.parse("2.0.0").compareTo(Version.parse("1.10.0")) > 0);
        });

        check("compareTo returns zero exactly when equals says true", () -> {
            expectEquals(0, Version.parse("1.2.3").compareTo(Version.parse("1.2.3")));
            expectTrue("different versions must not compare equal",
                Version.parse("1.2.3").compareTo(Version.parse("1.2.4")) != 0);
        });

        check("a TreeSet iterates ascending and drops the equal copy", () -> {
            TreeSet<Version> sorted = new TreeSet<>();
            for (String s : new String[] { "2.0.0", "1.10.0", "1.9.0", "1.10.0", "1.2.3" }) {
                sorted.add(Version.parse(s));
            }
            expectEquals(List.of("1.2.3", "1.9.0", "1.10.0", "2.0.0"), asText(sorted));
        });

        // --- the registry -----------------------------------------------------------------
        check("latest is the maximum, and an empty registry has no latest", () -> {
            Registry empty = new Registry();
            expectEquals(Optional.empty(), empty.latest());

            Registry r = registryOf("1.9.0", "2.0.0", "1.10.0");
            expectEquals("2.0.0", r.latest().orElseThrow().toString());

            r.add(Version.parse("10.0.0"));
            expectEquals("10.0.0", r.latest().orElseThrow().toString());
        });

        check("contains answers for a fresh equal copy and says no to a stranger", () -> {
            Registry r = registryOf("1.9.0", "2.0.0");
            expectTrue("an equal copy of 1.9.0 is in there", r.contains(Version.parse("1.9.0")));
            expectTrue("3.0.0 is not", !r.contains(Version.parse("3.0.0")));
        });

        check("all() is sorted, live, and refuses to be modified", () -> {
            Registry r = registryOf("2.0.0", "1.9.0", "1.10.0");

            SortedSet<Version> view = r.all();      // held across the add, deliberately
            expectEquals(List.of("1.9.0", "1.10.0", "2.0.0"), asText(view));
            expectThrows(UnsupportedOperationException.class, () -> view.add(Version.parse("3.0.0")));

            // The reference we already hold must show the new version. A defensive copy
            // would still be sitting on three elements here, and that is the difference.
            r.add(Version.parse("0.1.0"));
            expectEquals(List.of("0.1.0", "1.9.0", "1.10.0", "2.0.0"), asText(view));
            expectEquals(List.of("0.1.0", "1.9.0", "1.10.0", "2.0.0"), asText(r.all()));
            expectThrows(UnsupportedOperationException.class, () -> view.remove(Version.parse("2.0.0")));
        });

        // --- behaviour as a parameter: Predicate and Supplier -----------------------------
        check("matching runs the predicate you passed, whatever it is", () -> {
            Registry r = registryOf("1.9.0", "2.0.0", "1.10.0", "3.1.4", "1.2.3");

            expectEquals(List.of("1.2.3", "1.9.0", "1.10.0"), asText(r.matching(v -> v.major() == 1)));
            expectEquals(List.of("1.9.0", "1.10.0", "2.0.0"), asText(r.matching(v -> v.patch() == 0)));
            expectEquals(List.of("3.1.4"), asText(r.matching(v -> v.major() > 2)));
            expectEquals(List.of("1.2.3", "1.9.0", "1.10.0", "2.0.0", "3.1.4"), asText(r.matching(v -> true)));
        });

        check("matching returns an empty list, never null, and that list is unmodifiable", () -> {
            Registry r = registryOf("1.9.0", "2.0.0");
            List<Version> none = r.matching(v -> v.major() == 99);
            expectTrue("matching must not return null", none != null);
            expectEquals(0, none.size());
            expectThrows(UnsupportedOperationException.class, () -> none.add(Version.parse("1.0.0")));
            expectThrows(UnsupportedOperationException.class,
                () -> r.matching(v -> true).add(Version.parse("1.0.0")));
        });

        check("latestOrElse leaves the supplier alone when there IS a latest", () -> {
            Counter calls = new Counter();
            Supplier<Version> fallback = () -> { calls.n++; return Version.parse("0.0.1"); };

            Registry r = registryOf("1.9.0", "2.0.0");
            expectEquals("2.0.0", r.latestOrElse(fallback).toString());
            expectEquals(0, calls.n);

            // and again, with a different registry, so one lucky case cannot carry it
            Registry r2 = registryOf("4.5.6");
            expectEquals("4.5.6", r2.latestOrElse(fallback).toString());
            expectEquals(0, calls.n);
        });

        check("latestOrElse calls the supplier exactly once when the registry is empty", () -> {
            Counter calls = new Counter();
            Supplier<Version> fallback = () -> { calls.n++; return Version.parse("0.0.1"); };

            expectEquals("0.0.1", new Registry().latestOrElse(fallback).toString());
            expectEquals(1, calls.n);
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. Your Version is safe to use as a key, and the sets agree.");
    }

    // --- fixtures -------------------------------------------------------------
    static final class Counter { int n; }

    static Registry registryOf(String... texts) {
        Registry r = new Registry();
        for (String t : texts) r.add(Version.parse(t));
        return r;
    }

    static List<String> asText(Iterable<Version> versions) {
        List<String> out = new ArrayList<>();
        for (Version v : versions) out.add(v.toString());
        return out;
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectTrue(String what, boolean got) {
        if (!got) throw new AssertionError(what);
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
