package finale;

import java.net.ConnectException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * The specification for the finale. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Eleven tests, and every one of them is really a question about App.java.
 * Make every test green.
 */
public class RunTests {

    static final String ANN  = "{\"id\":1,\"owner\":\"ann\",\"balancePaise\":10000}";
    static final String BOB  = "{\"id\":2,\"owner\":\"bob\",\"balancePaise\":500}";
    static final String CARA = "{\"id\":7,\"owner\":\"cara\",\"balancePaise\":4200}";

    static int passed = 0, failed = 0;

    /** Held in a field on purpose. java.util.logging keeps its loggers weakly, so a level set on a
     *  logger nobody holds is collected again before Tomcat ever logs through it. */
    static final Logger HUSH = Logger.getLogger("org.apache.catalina.loader.WebappClassLoaderBase");

    static App app;
    static final HttpClient HTTP = HttpClient.newHttpClient();
    /** Used once, on an App that should be gone: it must not wait around. */
    static final HttpClient IMPATIENT = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(4)).build();

    public static void main(String[] args) {

        Logger.getLogger("").setLevel(Level.WARNING);   // Tomcat narrates itself at INFO; hush it
        HUSH.setLevel(Level.SEVERE);                   // and its leak detector, which talks at WARNING

        // --- one root wired the whole graph -------------------------------------------------
        check("App.start(0) boots and GET /accounts lists the two seeded accounts", () -> {
            app = App.start(0);
            HttpResponse<String> r = get(app, "/accounts");
            expectEquals(200, r.statusCode());
            if (!contentType(r).startsWith("application/json")) {
                throw new AssertionError("expected application/json but got [" + contentType(r) + "]");
            }
            expectEquals("[" + ANN + "," + BOB + "]", r.body());
        });

        check("an account saved through app.repository() shows up over HTTP: one graph, one instance", () -> {
            // One graph means one repository object, handed to the service once and kept in a field.
            // A repository() that says `return new JdbcAccountRepository(ds)` would still read the
            // same rows, so the reads below cannot see the difference. This line can.
            if (app.repository() != app.repository()) {
                throw new AssertionError("two calls to repository() returned two different objects:"
                        + " the root is building a new one each time instead of handing out the one it wired");
            }
            app.repository().save(new Account(7, "cara", 4200));
            expectEquals(CARA, get(app, "/accounts/7").body());
            expectEquals("[" + ANN + "," + BOB + "," + CARA + "]", get(app, "/accounts").body());
            app.repository().save(new Account(7, "cara", 4900));
            expectEquals("{\"id\":7,\"owner\":\"cara\",\"balancePaise\":4900}", get(app, "/accounts/7").body());
            app.repository().save(new Account(7, "cara", 4200));
        });

        // --- the servlet translates, the service and the repository never mention HTTP --------
        check("a missing account is 404 and an unreadable id is 400, both as JSON", () -> {
            HttpResponse<String> missing = get(app, "/accounts/999");
            expectEquals(404, missing.statusCode());
            expectEquals("{\"error\":\"no account 999\"}", missing.body());
            expectEquals(404, get(app, "/accounts/4242").statusCode());
            expectEquals("{\"error\":\"no account 4242\"}", get(app, "/accounts/4242").body());

            HttpResponse<String> nonsense = get(app, "/accounts/abc");
            expectEquals(400, nonsense.statusCode());
            expectEquals("{\"error\":\"id must be a number\"}", nonsense.body());

            HttpResponse<String> noAmount = post(app, "/accounts/transfer", "from=1&to=2&amount=0");
            expectEquals(400, noAmount.statusCode());
            contains(noAmount.body(), "amount must be positive");
            expectEquals(400, post(app, "/accounts/transfer", "from=1&to=2&amount=-5").statusCode());
            expectEquals(400, post(app, "/accounts/transfer", "from=1&to=2&amount=lots").statusCode());
            expectEquals(404, post(app, "/accounts/transfer", "from=1&to=999&amount=100").statusCode());
            expectEquals(404, post(app, "/accounts/transfer", "from=888&to=1&amount=100").statusCode());
        });

        // --- the money actually moves, in one transaction ------------------------------------
        check("POST /accounts/transfer moves exactly the amount asked for", () -> {
            HttpResponse<String> r = post(app, "/accounts/transfer", "from=1&to=2&amount=2500");
            expectEquals(200, r.statusCode());
            expectEquals("{\"ok\":true}", r.body());
            expectEquals("{\"id\":1,\"owner\":\"ann\",\"balancePaise\":7500}", get(app, "/accounts/1").body());
            expectEquals("{\"id\":2,\"owner\":\"bob\",\"balancePaise\":3000}", get(app, "/accounts/2").body());

            expectEquals(200, post(app, "/accounts/transfer", "from=7&to=1&amount=200").statusCode());
            expectEquals("{\"id\":7,\"owner\":\"cara\",\"balancePaise\":4000}", get(app, "/accounts/7").body());
            expectEquals("{\"id\":1,\"owner\":\"ann\",\"balancePaise\":7700}", get(app, "/accounts/1").body());
        });

        check("a transfer bigger than the balance is a 409 and nothing moves", () -> {
            HttpResponse<String> r = post(app, "/accounts/transfer", "from=2&to=1&amount=999999");
            expectEquals(409, r.statusCode());
            contains(r.body(), "cannot send");
            expectEquals("{\"id\":1,\"owner\":\"ann\",\"balancePaise\":7700}", get(app, "/accounts/1").body());
            expectEquals("{\"id\":2,\"owner\":\"bob\",\"balancePaise\":3000}", get(app, "/accounts/2").body());

            expectEquals(409, post(app, "/accounts/transfer", "from=7&to=2&amount=4001").statusCode());
            expectEquals("{\"id\":7,\"owner\":\"cara\",\"balancePaise\":4000}", get(app, "/accounts/7").body());
            expectEquals(200, post(app, "/accounts/transfer", "from=7&to=2&amount=4000").statusCode());
            expectEquals("{\"id\":7,\"owner\":\"cara\",\"balancePaise\":0}", get(app, "/accounts/7").body());
        });

        // --- a cross cutting concern, wired once at the root ---------------------------------
        check("the filter the root registered logged every one of those requests", () -> {
            app.log().clear();
            get(app, "/accounts");
            get(app, "/accounts/999");
            post(app, "/accounts/transfer", "from=1&to=2&amount=0");
            post(app, "/accounts/transfer", "from=1&to=2&amount=100");
            expectEquals(List.of("GET /accounts -> 200",
                                 "GET /accounts/999 -> 404",
                                 "POST /accounts/transfer -> 400",
                                 "POST /accounts/transfer -> 200"),
                    app.log().lines());
        });

        // --- Supplier<T>: the root decides what to build without building it -----------------
        check("booting builds no ReportRenderer at all", () -> {
            ReportRenderer.BUILDS.set(0);
            App lazy = App.start(0);
            try {
                expectEquals(0, ReportRenderer.BUILDS.get());
                expectEquals(200, get(lazy, "/accounts").statusCode());
                expectEquals(0, ReportRenderer.BUILDS.get());       // still nobody asked for a report
            } finally {
                quietStop(lazy);
            }
        });

        check("the first report builds it, and the second one does not", () -> {
            ReportRenderer.BUILDS.set(0);
            App reporting = App.start(0);
            try {
                HttpResponse<String> first = get(reporting, "/accounts/report");
                expectEquals(200, first.statusCode());
                expectEquals("report: 2 accounts holding 10500 paise", first.body());
                expectEquals(1, ReportRenderer.BUILDS.get());
                // Move the numbers, then ask again. A servlet that writes a remembered string
                // instead of calling render() answers with yesterday's figures.
                reporting.repository().save(new Account(7, "cara", 4200));
                expectEquals("report: 3 accounts holding 14700 paise", get(reporting, "/accounts/report").body());
                expectEquals(1, ReportRenderer.BUILDS.get());
            } finally {
                quietStop(reporting);
            }
        });

        check("20 requests at once: one renderer, and every answer belongs to the id that asked for it", () -> {
            // Twenty threads, four different questions, one servlet instance. Park the parsed id in
            // a field instead of a local and one of these twenty comes back with somebody else's answer.
            List<String> paths = new ArrayList<>();
            List<String> wanted = new ArrayList<>();
            for (int i = 0; i < 20; i++) {
                if (i % 4 == 0)      { paths.add("/accounts/report"); wanted.add("report: 2 accounts holding 10500 paise"); }
                else if (i % 4 == 1) { paths.add("/accounts/1");      wanted.add(ANN); }
                else if (i % 4 == 2) { paths.add("/accounts/2");      wanted.add(BOB); }
                else                 { paths.add("/accounts/999");    wanted.add("{\"error\":\"no account 999\"}"); }
            }
            for (int round = 1; round <= 3; round++) {
                ReportRenderer.BUILDS.set(0);
                App racing = App.start(0);
                try {
                    List<String> got = parallel(racing, paths);
                    for (int i = 0; i < paths.size(); i++) {
                        if (!wanted.get(i).equals(got.get(i))) {
                            throw new AssertionError("round " + round + ": GET " + paths.get(i) + " answered ["
                                    + got.get(i) + "] but should have answered [" + wanted.get(i) + "]."
                                    + " One instance, many threads: per request state goes in a local, never in a field");
                        }
                    }
                    if (ReportRenderer.BUILDS.get() != 1) {
                        throw new AssertionError("round " + round + ": five concurrent reports built "
                                + ReportRenderer.BUILDS.get() + " renderers, so the memoised Supplier is not thread safe");
                    }
                } finally {
                    quietStop(racing);
                }
            }
        });

        // --- the root owns the lifecycle and the configuration -------------------------------
        check("stop() really stops, and a fresh App boots a fresh database", () -> {
            int deadPort = app.port();                 // ask before stopping: a stopped connector reports -1
            app.stop();
            // ConnectException, not a timeout: a stop() that forgets destroy() leaves the socket
            // bound and this request would hang rather than bounce.
            expectThrows(ConnectException.class, () -> IMPATIENT.send(
                    HttpRequest.newBuilder(URI.create("http://localhost:" + deadPort + "/accounts"))
                            .timeout(Duration.ofSeconds(4)).GET().build(),
                    HttpResponse.BodyHandlers.ofString()));
            App second = App.start(0);
            try {
                expectEquals("[" + ANN + "," + BOB + "]", get(second, "/accounts").body());
                expectEquals(404, get(second, "/accounts/7").statusCode());   // cara belonged to the old one
            } finally {
                quietStop(second);
            }
        });

        check("two Apps at once keep their money to themselves", () -> {
            App left = App.start(0);
            App right = App.start(0);
            try {
                expectEquals(200, post(left, "/accounts/transfer", "from=1&to=2&amount=2000").statusCode());
                expectEquals("{\"id\":1,\"owner\":\"ann\",\"balancePaise\":8000}", get(left, "/accounts/1").body());
                expectEquals(ANN, get(right, "/accounts/1").body());
                expectEquals(BOB, get(right, "/accounts/2").body());
                if (left.port() == right.port()) throw new AssertionError("both Apps claim port " + left.port());
            } finally {
                quietStop(left);
                quietStop(right);
            }
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. One class wires the lot, and that class is the one Spring replaces.");
    }

    // --- talking to an App ----------------------------------------------------------
    static URI uri(App target, String path) {
        if (target == null) throw new AssertionError("there is no App to talk to");
        return URI.create("http://localhost:" + target.port() + path);
    }

    static HttpResponse<String> get(App target, String path) throws Exception {
        return HTTP.send(HttpRequest.newBuilder(uri(target, path)).GET().build(), HttpResponse.BodyHandlers.ofString());
    }

    static HttpResponse<String> post(App target, String path, String form) throws Exception {
        return HTTP.send(HttpRequest.newBuilder(uri(target, path))
                        .header("Content-Type", "application/x-www-form-urlencoded")
                        .POST(HttpRequest.BodyPublishers.ofString(form)).build(),
                HttpResponse.BodyHandlers.ofString());
    }

    static String contentType(HttpResponse<?> r) {
        return r.headers().firstValue("Content-Type").orElse("").toLowerCase().replace(" ", "");
    }

    /** Fires one request per path, all at the same moment, and hands the bodies back in that order. */
    static List<String> parallel(App target, List<String> paths) throws Exception {
        ExecutorService pool = Executors.newFixedThreadPool(paths.size());
        List<Callable<String>> jobs = new ArrayList<>();
        for (String path : paths) jobs.add(() -> get(target, path).body());
        List<String> bodies = new ArrayList<>();
        try {
            for (Future<String> f : pool.invokeAll(jobs)) bodies.add(f.get());
        } finally {
            pool.shutdownNow();
        }
        return bodies;
    }

    static void quietStop(App target) {
        try {
            if (target != null) target.stop();
        } catch (RuntimeException ignored) {
            // a test has already failed if this happens; do not bury it under a second error
        }
    }

    static void contains(String body, String wanted) {
        if (body == null || !body.contains(wanted)) {
            throw new AssertionError("expected a body containing [" + wanted + "] but got [" + body + "]");
        }
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
