package connect;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * The specification for part 1 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Nine tests, and between them they cover the whole round trip: find a driver,
 * open a connection, shape a table, put rows in, get objects back. Two of them read
 * your source, because some of what today teaches does not show up in a return value.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- the driver, and where it came from --------------------------------
        check("Db.open() hands back a live H2 connection, and no file in this package says Class.forName", () -> {
            try (Connection c = Db.open()) {
                if (c == null) throw new AssertionError("Db.open() returned null");
                if (c.isClosed()) throw new AssertionError("Db.open() returned a closed connection");
                expectEquals("H2", c.getMetaData().getDatabaseProductName());
            }
            expectEquals(true, Db.URL.startsWith("jdbc:h2:mem:"));
            for (String line : sourceLines()) {   // this loop reads the .java files next to you
                if (line.contains("Class.forName")) {
                    throw new AssertionError("the driver loads itself through ServiceLoader, so this line is dead weight: " + line.trim());
                }
            }
        });

        // --- DDL, and asking the database what it has --------------------------
        check("create builds the table, and DatabaseMetaData can see it afterwards", () -> {
            try (Connection c = Db.open()) {
                Schema.reset(c);
                expectEquals(false, Schema.exists(c));
                Schema.create(c);
                expectEquals(true, Schema.exists(c));
                try (ResultSet rs = c.getMetaData().getTables(null, null, "ACCOUNT", new String[]{"TABLE"})) {
                    expectEquals(true, rs.next());
                    expectEquals("ACCOUNT", rs.getString("TABLE_NAME"));
                }
            }
        });

        check("create twice in a row is harmless, because the DDL says IF NOT EXISTS", () -> {
            try (Connection c = Db.open()) {
                Schema.reset(c);
                Schema.create(c);
                AccountDao.insert(c, "already here", 42);
                Schema.create(c);
                expectEquals(true, Schema.exists(c));
                expectEquals(1, AccountDao.findAll(c).size());
                expectEquals("already here", AccountDao.findAll(c).get(0).owner());
            }
        });

        // --- insert, generated key, and the mapper -----------------------------
        check("insert returns the generated id and findById maps the row back to an equal Account", () -> {
            try (Connection c = fresh()) {
                long ana = AccountDao.insert(c, "ana", 10_000);
                long bo  = AccountDao.insert(c, "bo", 5);
                expectEquals(true, ana > 0);
                expectEquals(true, bo > ana);
                expectEquals(new Account(ana, "ana", 10_000), AccountDao.findById(c, ana).orElseThrow());
                expectEquals(new Account(bo, "bo", 5), AccountDao.findById(c, bo).orElseThrow());
            }
        });

        check("findById of an id that is not there gives Optional.empty, not null and not an exception", () -> {
            try (Connection c = fresh()) {
                long ana = AccountDao.insert(c, "ana", 100);
                Optional<Account> missing = AccountDao.findById(c, ana + 1);
                if (missing == null) throw new AssertionError("findById returned null instead of an Optional");
                expectEquals(true, missing.isEmpty());
                expectEquals(Optional.empty(), AccountDao.findById(c, 4242));
                expectEquals(Optional.empty(), AccountDao.findById(c, -1));
                expectEquals(true, AccountDao.findById(c, ana).isPresent());
            }
        });

        // --- the cursor loop ----------------------------------------------------
        check("three inserts, then findAll returns all three in ascending id order", () -> {
            try (Connection c = fresh()) {
                long ana = AccountDao.insert(c, "ana", 10_000);
                long bo  = AccountDao.insert(c, "bo", 5_000);
                long cy  = AccountDao.insert(c, "cy", 0);
                expectEquals(List.of(new Account(ana, "ana", 10_000),
                                     new Account(bo, "bo", 5_000),
                                     new Account(cy, "cy", 0)),
                             AccountDao.findAll(c));
            }
            try (Connection c = fresh()) {
                expectEquals(List.of(), AccountDao.findAll(c));
                long only = AccountDao.insert(c, "solo", 7);
                expectEquals(List.of(new Account(only, "solo", 7)), AccountDao.findAll(c));
            }
        });

        // --- binding, not gluing -------------------------------------------------
        check("a quote in the data is data: O'Brien and a sabotage string both round-trip unchanged", () -> {
            try (Connection c = fresh()) {
                String nasty = "x'); DROP TABLE account; --";
                long ob = AccountDao.insert(c, "O'Brien", 700);
                long sneaky = AccountDao.insert(c, nasty, 1);
                expectEquals("O'Brien", AccountDao.findById(c, ob).orElseThrow().owner());
                expectEquals(nasty, AccountDao.findById(c, sneaky).orElseThrow().owner());
                expectEquals(true, Schema.exists(c));
                expectEquals(2, AccountDao.findAll(c).size());
            }
        });

        // --- and the same thing again, this time by reading what you wrote --------
        check("AccountDao binds through a PreparedStatement: no createStatement, no SQL built with +, every statement closed by try-with-resources", () -> {
            String src = code(sourceOf("AccountDao.java"));
            String flat = masked(src);

            if (flat.contains("createStatement(")) {
                throw new AssertionError("AccountDao calls createStatement(): every value in this class came from a caller, "
                        + "so it has to travel as a bound parameter, not as text in the SQL");
            }
            int prepared = flat.split(Pattern.quote("prepareStatement("), -1).length - 1;
            if (prepared < 3) {
                throw new AssertionError("expected a prepareStatement per query but found " + prepared);
            }
            for (String arg : firstArgs(src, flat, "prepareStatement(")) {
                boolean given = arg.equals("INSERT") || arg.equals("FIND_BY_ID") || arg.equals("FIND_ALL");
                boolean literalWithHoles = arg.startsWith("\"") && arg.contains("?");
                if (!given && !literalWithHoles) {
                    throw new AssertionError("prepareStatement(" + arg + "): prepare one of the SQL constants you were given. "
                            + "A string assembled somewhere else is how the glued version sneaks back in");
                }
            }
            String glued = gluedSql(src);
            if (glued != null) {
                throw new AssertionError("this SQL is concatenated with +: " + glued
                        + "  -- that is the exact hole the ? closes, and no amount of quote-doubling fixes it");
            }
            if (!src.contains("ORDER BY id")) {
                throw new AssertionError("FIND_ALL has lost its ORDER BY id, and findAll promises ascending id order");
            }
            for (String call : List.of("prepareStatement(", "executeQuery(", "getGeneratedKeys(")) {
                for (int at : occurrences(flat, call)) {
                    if (!insideTryHeader(flat, at)) {
                        throw new AssertionError("this " + call + ") is not opened by a try-with-resources, "
                                + "so it stays open when something throws: line " + lineOf(src, at));
                    }
                }
            }
        });

        // --- the last line of defence -------------------------------------------
        check("the CHECK constraint refuses a negative balance, and the table is untouched afterwards", () -> {
            try (Connection c = fresh()) {
                AccountDao.insert(c, "ana", 10_000);
                AccountDao.insert(c, "bo", 5_000);
                SQLIntegrityConstraintViolationException e = expectThrows(
                        SQLIntegrityConstraintViolationException.class,
                        () -> AccountDao.insert(c, "thief", -1));
                String state = String.valueOf(e.getSQLState());
                if (!state.startsWith("23")) {
                    throw new AssertionError("expected an SQLState in class 23 (integrity constraint) but got " + state);
                }
                expectEquals(2, AccountDao.findAll(c).size());
            }
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. You can find a driver, shape a table and turn rows into objects.");
    }

    // --- fixtures --------------------------------------------------------------

    /** A connection onto an empty account table. */
    static Connection fresh() throws SQLException {
        Connection c = Db.open();
        Schema.reset(c);
        Schema.create(c);
        return c;
    }

    /** Every line of source in this package except this file. */
    static List<String> sourceLines() throws IOException {
        List<String> out = new ArrayList<>();
        try (Stream<Path> files = Files.list(packageDir())) {
            for (Path p : files.toList()) {
                if (p.getFileName().toString().endsWith(".java")
                        && !p.getFileName().toString().equals("RunTests.java")) {
                    out.addAll(Files.readAllLines(p));
                }
            }
        }
        return out;
    }

    /** One file of yours, as text. */
    static String sourceOf(String fileName) throws IOException {
        Path p = packageDir().resolve(fileName);
        if (!Files.isRegularFile(p)) throw new AssertionError("expected " + fileName + " next to RunTests.java");
        return Files.readString(p);
    }

    /** A file that only this part has, so the search cannot land in another part's folder. */
    static final String MARKER = "Schema.java";

    /**
     * Where your .java files are. Looked for relative to the working directory AND relative to
     * the class files themselves, because an IDE runs you from the project root while run.sh
     * runs you from this folder. Never silently returns nothing: a check you cannot see is worse
     * than a check that fails.
     */
    static Path packageDir() {
        String pkg = RunTests.class.getPackageName();
        List<Path> roots = new ArrayList<>();
        try {
            var cs = RunTests.class.getProtectionDomain().getCodeSource();
            if (cs != null && cs.getLocation() != null) {
                Path p = Path.of(cs.getLocation().toURI());
                roots.add(Files.isDirectory(p) ? p : p.getParent());
            }
        } catch (Exception ignored) {
            // an exotic class loader; the working directory will have to do
        }
        roots.add(Path.of("").toAbsolutePath());
        for (Path root : roots) {
            Path base = root;
            for (int up = 0; up < 4 && base != null; up++, base = base.getParent()) {
                Path hit = lookFor(base, pkg, 4);
                if (hit != null) return hit;
            }
        }
        throw new AssertionError("cannot find the " + pkg + " sources from " + Path.of("").toAbsolutePath()
                + ": run this part with ./run.sh or .\\run.cmd from its own folder");
    }

    private static Path lookFor(Path base, String pkg, int depth) {
        if (base == null || !Files.isDirectory(base)) return null;
        if (base.getFileName() != null && base.getFileName().toString().equals(pkg)
                && Files.isRegularFile(base.resolve(MARKER))) return base;
        if (depth <= 0) return null;
        try (Stream<Path> kids = Files.list(base)) {
            for (Path k : kids.toList()) {
                String name = k.getFileName().toString();
                if (!Files.isDirectory(k) || name.startsWith(".") || name.equals("lib")) continue;
                Path hit = lookFor(k, pkg, depth - 1);
                if (hit != null) return hit;
            }
        } catch (IOException | UncheckedIOException ignored) {
            // unreadable folder: keep looking elsewhere
        }
        return null;
    }

    // --- enough source reading to tell binding from gluing ---------------------

    /** The source with every comment blanked out, same length, so an offset still means something. */
    static String code(String src) {
        char[] out = src.toCharArray();
        int i = 0, n = src.length();
        while (i < n) {
            char ch = src.charAt(i);
            if (ch == '"' && src.startsWith("\"\"\"", i)) {
                int j = src.indexOf("\"\"\"", i + 3);
                i = j < 0 ? n : j + 3;
            } else if (ch == '"' || ch == '\'') {
                i++;
                while (i < n && src.charAt(i) != ch) i += src.charAt(i) == '\\' ? 2 : 1;
                i++;
            } else if (ch == '/' && i + 1 < n && src.charAt(i + 1) == '/') {
                while (i < n && src.charAt(i) != '\n') out[i++] = ' ';
            } else if (ch == '/' && i + 1 < n && src.charAt(i + 1) == '*') {
                int j = src.indexOf("*/", i + 2);
                j = j < 0 ? n : j + 2;
                while (i < j) { if (out[i] != '\n') out[i] = ' '; i++; }
            } else {
                i++;
            }
        }
        return new String(out);
    }

    /** The same text with the inside of every string blanked, so a bracket in SQL is not a bracket in Java. */
    static String masked(String code) {
        char[] out = code.toCharArray();
        int i = 0, n = code.length();
        while (i < n) {
            char ch = code.charAt(i);
            if (ch == '"' || ch == '\'') {
                i++;
                while (i < n && code.charAt(i) != ch) {
                    if (code.charAt(i) == '\\' && i + 1 < n) out[i++] = ' ';
                    out[i++] = ' ';
                }
                i++;
            } else {
                i++;
            }
        }
        return new String(out);
    }

    static List<Integer> occurrences(String text, String needle) {
        List<Integer> out = new ArrayList<>();
        for (int at = text.indexOf(needle); at >= 0; at = text.indexOf(needle, at + 1)) out.add(at);
        return out;
    }

    /** The first argument of every call to this method, as you wrote it. */
    static List<String> firstArgs(String code, String flat, String call) {
        List<String> out = new ArrayList<>();
        for (int at : occurrences(flat, call)) {
            int i = at + call.length(), start = i, depth = 1;
            while (i < flat.length() && depth > 0) {
                char ch = flat.charAt(i);
                if (ch == '(') depth++;
                else if (ch == ')') { depth--; if (depth == 0) break; }
                else if (ch == ',' && depth == 1) break;
                i++;
            }
            out.add(code.substring(start, Math.min(i, code.length())).trim());
        }
        return out;
    }

    /** Is this offset inside the bracket of a try-with-resources? */
    static boolean insideTryHeader(String flat, int at) {
        Matcher m = Pattern.compile("\\btry\\s*\\(").matcher(flat);
        while (m.find()) {
            int i = m.end() - 1, depth = 0;
            for (; i < flat.length(); i++) {
                char ch = flat.charAt(i);
                if (ch == '(') depth++;
                else if (ch == ')' && --depth == 0) break;
            }
            if (at > m.start() && at < i) return true;
        }
        return false;
    }

    /** A SQL string with a + stuck to it, which is the whole bug in one pattern. */
    static String gluedSql(String code) {
        Matcher lit = Pattern.compile("\"(?:\\\\.|[^\"\\\\])*\"").matcher(code);
        Pattern sql = Pattern.compile("(?i)\\b(select|insert|update|delete|from|where|values|like)\\b");
        while (lit.find()) {
            if (!sql.matcher(lit.group()).find()) continue;
            String before = code.substring(Math.max(0, lit.start() - 4), lit.start()).trim();
            String after = code.substring(lit.end(), Math.min(code.length(), lit.end() + 4)).trim();
            if (before.endsWith("+") || after.startsWith("+")) return lit.group();
        }
        return null;
    }

    static int lineOf(String src, int at) {
        return (int) src.substring(0, Math.min(at, src.length())).chars().filter(ch -> ch == '\n').count() + 1;
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static <T extends Throwable> T expectThrows(Class<T> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return expected.cast(t);
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
