package finale;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * The specification for the finale. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your class must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Nineteen tests, and between them they use merge, computeIfAbsent, a PriorityQueue,
 * a TreeMap, an Optional and both kinds of read-only map.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- counting with merge ----------------------------------------------------------
        check("case folds away and repeats add up", () -> {
            WordStats s = new WordStats();
            s.add("The cat the CAT");
            expectEquals(2, s.count("the"));
            expectEquals(2, s.count("cat"));
            expectEquals(2, s.frequencies().size());

            s.add("dog DOG dog, cat!");
            expectEquals(3, s.count("dog"));
            expectEquals(3, s.count("cat"));
            expectEquals(2, s.count("the"));
            expectEquals(3, s.frequencies().size());
        });

        check("punctuation and runs of spaces split words, they do not join them", () -> {
            WordStats s = new WordStats();
            s.add("well-known   ideas; well aimed!");
            expectEquals(2, s.count("well"));
            expectEquals(1, s.count("known"));
            expectEquals(1, s.count("ideas"));
            expectEquals(1, s.count("aimed"));
            expectEquals(0, s.count("well-known"));
            expectEquals(4, s.frequencies().size());
        });

        check("case folding uses Locale.ROOT, so a Turkish machine counts the same words", () -> {
            Locale original = Locale.getDefault();
            try {
                Locale.setDefault(Locale.forLanguageTag("tr"));   // 'I' folds to a DOTLESS i here
                WordStats s = new WordStats();
                s.add("INDIA India india");
                expectEquals(3, s.count("india"));
                expectEquals(1, s.frequencies().size());
                expectEquals(List.of("india"), s.words());
                expectEquals(Optional.of("india"), s.mostFrequent());
            } finally {
                Locale.setDefault(original);
            }
        });

        check("a word never seen counts zero, and asking does not create it", () -> {
            WordStats s = new WordStats();
            s.add("one two");
            expectEquals(0, s.count("three"));
            expectEquals(0, s.count(""));
            expectEquals(2, s.frequencies().size());
        });

        // --- merge returning null deletes the entry ---------------------------------------
        check("removing every occurrence deletes the word, it does not park it at zero", () -> {
            WordStats s = new WordStats();
            s.add("cat cat dog dog dog");

            s.remove("cat", 2);
            expectEquals(0, s.count("cat"));
            expectTrue("cat must be GONE from frequencies, not present with 0",
                !s.frequencies().containsKey("cat"));
            expectEquals(1, s.frequencies().size());
            expectEquals(List.of("dog"), s.words());
        });

        check("removing some of them just lowers the count", () -> {
            WordStats s = new WordStats();
            s.add("cat cat cat cat");
            s.remove("cat", 1);
            expectEquals(3, s.count("cat"));
            s.remove("cat", 2);
            expectEquals(1, s.count("cat"));
            expectTrue("cat is still there", s.frequencies().containsKey("cat"));

            s.remove("lynx", 1);                    // a word this fixture has never seen
            expectEquals(1, s.frequencies().size());
            expectTrue("lynx must not have been invented", !s.frequencies().containsKey("lynx"));
            expectEquals(1, s.count("cat"));
        });

        check("over-removing, and removing a word that was never there, leave no wreckage", () -> {
            WordStats s = new WordStats();
            s.add("cat dog");

            s.remove("cat", 99);
            expectEquals(0, s.count("cat"));
            expectTrue("no negative entry for cat", !s.frequencies().containsKey("cat"));

            s.remove("hippo", 3);
            expectEquals(0, s.count("hippo"));
            expectTrue("no entry invented for hippo", !s.frequencies().containsKey("hippo"));

            // Two different never-seen words, because a guard that happens to reject one
            // particular string is not a guard. The map must not have grown at all.
            s.remove("quokka", 1);
            expectEquals(0, s.count("quokka"));
            expectTrue("no entry invented for quokka", !s.frequencies().containsKey("quokka"));
            expectEquals(1, s.frequencies().size());
            expectEquals(List.of("dog"), s.words());
        });

        // --- Optional, written rather than returned ---------------------------------------
        check("mostFrequent is empty when nothing has been counted", () -> {
            expectEquals(Optional.empty(), new WordStats().mostFrequent());

            WordStats emptied = new WordStats();
            emptied.add("solo");
            emptied.remove("solo", 1);
            expectEquals(Optional.empty(), emptied.mostFrequent());
        });

        check("mostFrequent picks the winner, and the alphabetically first of a tie", () -> {
            WordStats clear = new WordStats();
            clear.add("red red red blue blue green");
            expectEquals(Optional.of("red"), clear.mostFrequent());

            WordStats tied = new WordStats();
            tied.add("zebra apple mango");
            expectEquals(Optional.of("apple"), tied.mostFrequent());

            WordStats tiedHigher = new WordStats();
            tiedHigher.add("pear pear kiwi kiwi fig");
            expectEquals(Optional.of("kiwi"), tiedHigher.mostFrequent());
        });

        // --- top k with a bounded heap ----------------------------------------------------
        check("topK returns count descending, ties alphabetical", () -> {
            WordStats s = new WordStats();
            s.add("the the the cat cat dog");
            expectEquals(List.of("the"), s.topK(1));
            expectEquals(List.of("the", "cat"), s.topK(2));
            expectEquals(List.of("the", "cat", "dog"), s.topK(3));

            WordStats tied = new WordStats();
            tied.add("apple apple banana banana cherry");
            expectEquals(List.of("apple", "banana"), tied.topK(2));
        });

        check("a tie right at the k boundary keeps the alphabetically first word", () -> {
            WordStats s = new WordStats();
            s.add("zebra zebra zebra apple apple mango mango peach peach berry berry once");

            expectEquals(List.of("zebra", "apple"), s.topK(2));
            expectEquals(List.of("zebra", "apple", "berry"), s.topK(3));
            expectEquals(List.of("zebra", "apple", "berry", "mango"), s.topK(4));
            expectEquals(List.of("zebra", "apple", "berry", "mango", "peach"), s.topK(5));
            expectEquals(List.of("zebra", "apple", "berry", "mango", "peach", "once"), s.topK(6));
        });

        check("k past the end, and k of zero, come back quietly", () -> {
            WordStats s = new WordStats();
            s.add("one two two");
            expectEquals(List.of("two", "one"), s.topK(9));
            expectEquals(List.of(), s.topK(0));
            expectEquals(List.of(), new WordStats().topK(5));
        });

        // --- grouping with computeIfAbsent into a TreeMap ---------------------------------
        check("byFirstLetter groups under the first character, letters in order", () -> {
            WordStats s = new WordStats();
            s.add("mango apple avocado zebra banana apple");

            Map<Character, List<String>> grouped = s.byFirstLetter();
            expectEquals(List.of('a', 'b', 'm', 'z'), new ArrayList<>(grouped.keySet()));
            expectEquals(List.of("apple", "avocado"), grouped.get('a'));
            expectEquals(List.of("banana"), grouped.get('b'));
            expectEquals(List.of("mango"), grouped.get('m'));
            expectEquals(List.of("zebra"), grouped.get('z'));
        });

        check("byFirstLetter on a different vocabulary, so the order is not a coincidence", () -> {
            WordStats s = new WordStats();
            s.add("yak yam xenon walrus wombat wren otter");

            Map<Character, List<String>> grouped = s.byFirstLetter();
            expectEquals(List.of('o', 'w', 'x', 'y'), new ArrayList<>(grouped.keySet()));
            expectEquals(List.of("otter"), grouped.get('o'));
            expectEquals(List.of("walrus", "wombat", "wren"), grouped.get('w'));
            expectEquals(List.of("xenon"), grouped.get('x'));
            expectEquals(List.of("yak", "yam"), grouped.get('y'));
            expectEquals(List.of(), new ArrayList<>(new WordStats().byFirstLetter().keySet()));
        });

        // --- what you hand out, and what it promises --------------------------------------
        check("words() is sorted and cannot be added to", () -> {
            WordStats s = new WordStats();
            s.add("pear apple fig pear");
            expectEquals(List.of("apple", "fig", "pear"), s.words());
            expectThrows(UnsupportedOperationException.class, () -> s.words().add("x"));

            WordStats other = new WordStats();
            other.add("delta charlie bravo alpha");
            expectEquals(List.of("alpha", "bravo", "charlie", "delta"), other.words());
        });

        check("frequencies() is a snapshot: it does not move when the stats do", () -> {
            WordStats s = new WordStats();
            s.add("cat cat dog");
            Map<String, Integer> snapshot = s.frequencies();
            expectEquals(2, (int) snapshot.get("cat"));
            expectEquals(2, snapshot.size());

            s.add("cat bird bird bird");
            expectEquals(2, (int) snapshot.get("cat"));
            expectEquals(2, snapshot.size());
            expectTrue("bird must not appear in the old snapshot", !snapshot.containsKey("bird"));
            expectEquals(3, (int) s.frequencies().get("cat"));
        });

        check("frequencies() refuses writes", () -> {
            WordStats s = new WordStats();
            s.add("cat");
            expectThrows(UnsupportedOperationException.class, () -> s.frequencies().put("cat", 99));
            expectThrows(UnsupportedOperationException.class, () -> s.frequencies().remove("cat"));
            expectEquals(1, s.count("cat"));
        });

        check("index() is a live view: it moves when the stats do, and still refuses writes", () -> {
            WordStats s = new WordStats();
            s.add("cat cat dog");
            Map<String, Integer> view = s.index();
            expectEquals(2, (int) view.get("cat"));
            expectEquals(2, view.size());

            s.add("cat bird bird bird");
            expectEquals(3, (int) view.get("cat"));
            expectEquals(3, (int) view.get("bird"));
            expectEquals(3, view.size());

            s.remove("dog", 1);
            expectEquals(2, view.size());
            expectTrue("dog left through the view too", !view.containsKey("dog"));

            expectThrows(UnsupportedOperationException.class, () -> view.put("cat", 99));
        });

        check("the two of them side by side, which is the whole point of having both", () -> {
            WordStats s = new WordStats();
            s.add("alpha");
            Map<String, Integer> snapshot = s.frequencies();
            Map<String, Integer> view = s.index();

            s.add("beta gamma");
            expectEquals(1, snapshot.size());
            expectEquals(3, view.size());
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. One class, and it used most of the Collections framework properly.");
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectTrue(String what, boolean got) {
        if (!got) throw new AssertionError(what);
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
