package hello;

import java.net.ConnectException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * The specification for part 1 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Nine tests, and between them they walk a request in and a response out.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    /** Held in a field on purpose. java.util.logging keeps its loggers weakly, so a level set on a
     *  logger nobody holds is collected again before Tomcat ever logs through it. */
    static final Logger HUSH = Logger.getLogger("org.apache.catalina.loader.WebappClassLoaderBase");

    static Server server;
    static int port = 0;
    static final HttpClient HTTP = HttpClient.newHttpClient();
    /** Used once, on a server that should be gone: it must not wait around. */
    static final HttpClient IMPATIENT = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(4)).build();

    public static void main(String[] args) {

        Logger.getLogger("").setLevel(Level.WARNING);   // Tomcat narrates itself at INFO; hush it
        HUSH.setLevel(Level.SEVERE);                   // and its leak detector, which talks at WARNING

        // --- the container is yours to start and to end ---------------------------------------
        check("the server starts on port 0 and reports the real port the OS gave it", () -> {
            server = new Server(0);
            server.start();
            port = server.port();
            if (port <= 0 || port > 65535) {
                throw new AssertionError("port() returned " + port + ", which is not a port a connector is listening on");
            }
            // Any number between 1 and 65535 satisfies the line above, including one you typed in
            // yourself. So: a second server, also asked for port 0, while the first still holds its
            // socket. The OS cannot hand out the same port twice, so two different numbers is proof
            // that the 0 was passed on and the answer read back.
            Server second = new Server(0);
            second.start();
            int secondPort = second.port();
            second.stop();
            if (secondPort <= 0 || secondPort > 65535 || secondPort == port) {
                throw new AssertionError("a second server, also asked for port 0, reported " + secondPort
                        + " while the first one holds " + port + ": ask for 0 and the OS hands out two"
                        + " different free ports, so the number you were given is being ignored somewhere"
                        + " (a hard-coded port cannot bind twice, and a dead connector reports -1)");
            }
        });

        // --- doGet, parameters, the writer ----------------------------------------------------
        check("GET /hello?name=... answers 200 and greets the name it was given", () -> {
            HttpResponse<String> r = get("/hello?name=byts");
            expectEquals(200, r.statusCode());
            expectEquals("hello byts", r.body());
            expectEquals("hello ada", get("/hello?name=ada").body());
            expectEquals("hello a b", get("/hello?name=" + enc("a b")).body());
        });

        check("the reply is text/plain with an explicit UTF-8 charset, so an accented name arrives whole", () -> {
            HttpResponse<byte[]> r = bytes("/hello?name=" + enc("Zoë"));
            String ct = header(r, "Content-Type");
            expectEquals("text/plain;charset=utf-8", ct);
            expectEquals("hello Zoë", new String(r.body(), StandardCharsets.UTF_8));
            expectEquals("hello Åsa", new String(bytes("/hello?name=" + enc("Åsa")).body(), StandardCharsets.UTF_8));
        });

        check("a missing name and a blank name are both 400, and your body survives", () -> {
            HttpResponse<String> missing = get("/hello");
            expectEquals(400, missing.statusCode());
            expectEquals("name required", missing.body());
            HttpResponse<String> blank = get("/hello?name=" + enc("   "));
            expectEquals(400, blank.statusCode());
            expectEquals("name required", blank.body());
        });

        // --- what HttpServlet does for you ----------------------------------------------------
        check("POST /hello answers 405 although you never wrote a doPost", () -> {
            HttpResponse<String> r = post("/hello", "name=byts");
            expectEquals(405, r.statusCode());
        });

        check("GET /nothing answers 404: the mapper decides that, not your servlet", () -> {
            expectEquals(404, get("/nothing").statusCode());
            expectEquals(404, get("/hello/extra").statusCode());
        });

        // --- JSON by hand: status, header and body are three separate decisions ---------------
        check("GET /square?n=7 answers 200, application/json, and exactly the right object", () -> {
            HttpResponse<String> r = get("/square?n=7");
            expectEquals(200, r.statusCode());
            if (!header(r, "Content-Type").startsWith("application/json")) {
                throw new AssertionError("expected an application/json content type but got [" + header(r, "Content-Type") + "]");
            }
            expectEquals("{\"n\":7,\"square\":49}", r.body());
            expectEquals("{\"n\":-3,\"square\":9}", get("/square?n=-3").body());
            expectEquals("{\"n\":0,\"square\":0}", get("/square?n=0").body());
            expectEquals("{\"n\":12,\"square\":144}", get("/square?n=12").body());
        });

        check("bad input to /square is a 400 the client can parse, not an HTML page and not a 500", () -> {
            HttpResponse<String> r = get("/square?n=x");
            expectEquals(400, r.statusCode());
            if (!header(r, "Content-Type").startsWith("application/json")) {
                throw new AssertionError("expected an application/json content type but got [" + header(r, "Content-Type") + "]");
            }
            expectEquals("{\"error\":\"n must be an integer\"}", r.body());
            expectEquals(400, get("/square").statusCode());
            expectEquals("{\"error\":\"n must be an integer\"}", get("/square").body());
            expectEquals("{\"error\":\"n must be an integer\"}", get("/square?n=" + enc("7 ")).body());
        });

        // --- and the end of the lifecycle -----------------------------------------------------
        check("after stop() the port is dead: the connection is refused, not just ignored", () -> {
            if (server == null || port == 0) throw new AssertionError("the server never started, so there is nothing to stop");
            int deadPort = port;
            server.stop();
            // ConnectException, not a timeout: stop() without destroy() leaves the socket bound,
            // and then this request hangs instead of bouncing.
            expectThrows(ConnectException.class, () -> IMPATIENT.send(
                    HttpRequest.newBuilder(URI.create("http://localhost:" + deadPort + "/hello?name=byts"))
                            .timeout(Duration.ofSeconds(4)).GET().build(),
                    HttpResponse.BodyHandlers.ofString()));
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. You booted a container and answered HTTP with your own hands.");
    }

    // --- talking to the server ------------------------------------------------------
    static String url(String path) {
        if (port == 0) throw new AssertionError("the server is not up, so this request cannot be made");
        return "http://localhost:" + port + path;
    }

    static HttpResponse<String> get(String path) throws Exception {
        return HTTP.send(HttpRequest.newBuilder(URI.create(url(path))).GET().build(),
                HttpResponse.BodyHandlers.ofString());
    }

    static HttpResponse<byte[]> bytes(String path) throws Exception {
        return HTTP.send(HttpRequest.newBuilder(URI.create(url(path))).GET().build(),
                HttpResponse.BodyHandlers.ofByteArray());
    }

    static HttpResponse<String> post(String path, String form) throws Exception {
        return HTTP.send(HttpRequest.newBuilder(URI.create(url(path)))
                        .header("Content-Type", "application/x-www-form-urlencoded")
                        .POST(HttpRequest.BodyPublishers.ofString(form)).build(),
                HttpResponse.BodyHandlers.ofString());
    }

    static String header(HttpResponse<?> r, String name) {
        return r.headers().firstValue(name).orElse("").toLowerCase().replace(" ", "");
    }

    static String enc(String s) {
        return URLEncoder.encode(s, StandardCharsets.UTF_8);
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
