package finale;

import java.util.List;
import java.util.Objects;

/**
 * The specification for the finale. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Ten tests, and between them they join the two halves of the day.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- the formats have to read the accounts they are handed -------------------------
        check("plain format: one 'id: balance' line per account", () ->
            expectEquals("A: 500\nB: 0",
                new PlainFormat().format(List.of(new Account("A", 500), new Account("B", 0)))));

        check("plain format: no accounts, no lines", () ->
            expectEquals("", new PlainFormat().format(List.of())));

        check("plain format: three accounts keep their own ids and balances", () ->
            expectEquals("""
                            X: 1
                            Y: 20
                            Z: 300""",
                new PlainFormat().format(List.of(
                    new Account("X", 1), new Account("Y", 20), new Account("Z", 300)))));

        check("csv format: a header, then one row per account", () ->
            expectEquals("id,balance\nA,500\nB,0",
                new CsvFormat().format(List.of(new Account("A", 500), new Account("B", 0)))));

        check("csv format: no accounts, just the header", () ->
            expectEquals("id,balance", new CsvFormat().format(List.of())));

        check("csv format: three accounts keep their own ids and balances", () ->
            expectEquals("""
                            id,balance
                            X,1
                            Y,20
                            Z,300""",
                new CsvFormat().format(List.of(
                    new Account("X", 1), new Account("Y", 20), new Account("Z", 300)))));

        // --- DIP: the exporter hands the work to the format it was given -------------------
        check("the exporter returns the plain format's output unchanged", () ->
            expectEquals("P: 7",
                new StatementExporter(new PlainFormat()).export(List.of(new Account("P", 7)))));

        check("the exporter returns the csv format's output unchanged", () ->
            expectEquals("id,balance\nP,7\nQ,8",
                new StatementExporter(new CsvFormat())
                    .export(List.of(new Account("P", 7), new Account("Q", 8)))));

        check("the exporter accepts a brand new format it has never seen (OCP / DIP)", () -> {
            StatementFormat totalCount = accounts -> "accounts:" + accounts.size();
            expectEquals("accounts:2",
                new StatementExporter(totalCount).export(List.of(new Account("A", 1), new Account("B", 2))));
        });

        // --- encapsulation: the guarded balance is what the statement reports --------------
        check("an overdraw throws and moves nothing, and the statement says so", () -> {
            Account a = new Account("A", 100);
            expectThrows(IllegalArgumentException.class, () -> a.withdraw(150));
            a.withdraw(40);
            expectEquals("A: 60", new StatementExporter(new PlainFormat()).export(List.of(a)));
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. The pillars made the data, SOLID got it out of the building.");
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static void expectThrows(Class<? extends Throwable> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return;
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
