package transfer;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * The specification for part 2 of the capstone. DO NOT EDIT THIS FILE.
 * Read it top to bottom: it is exactly what your classes must do.
 * Run it from this part's folder with:   .\run.cmd   (Windows)   or   ./run.sh   (macOS / Linux)
 * Ten tests. Three of them fail for code that looks completely reasonable, and one
 * of them reads your source, because a ? that is not there does not show up in a result.
 * Make every test green.
 */
public class RunTests {

    static int passed = 0, failed = 0;

    public static void main(String[] args) {

        // --- the happy path, twice, with different numbers ---------------------
        check("a transfer moves the money as one unit", () -> {
            try (Connection c = fresh()) {
                TransferService.transfer(c, Db.ANA, Db.BO, 2_500);
                expectEquals(7_500, Db.balance(c, Db.ANA));
                expectEquals(7_500, Db.balance(c, Db.BO));

                TransferService.transfer(c, Db.BO, Db.OBRIEN, 300);
                expectEquals(7_200, Db.balance(c, Db.BO));
                expectEquals(1_000, Db.balance(c, Db.OBRIEN));
                expectEquals(7_500, Db.balance(c, Db.ANA));
            }
        });

        check("a transfer of the whole balance works, because the CHECK allows exactly zero", () -> {
            try (Connection c = fresh()) {
                TransferService.transfer(c, Db.OBRIEN, Db.BO, 700);
                expectEquals(0, Db.balance(c, Db.OBRIEN));
                expectEquals(5_700, Db.balance(c, Db.BO));
            }
        });

        // --- the database says no, and nothing moves ---------------------------
        check("an overdraft throws InsufficientFundsException and BOTH balances are untouched", () -> {
            try (Connection c = fresh()) {
                InsufficientFundsException e = expectThrows(InsufficientFundsException.class,
                        () -> TransferService.transfer(c, Db.ANA, Db.BO, 10_001));
                expectEquals(Db.ANA, e.from());
                expectEquals(Db.BO, e.to());
                expectEquals(10_001, e.cents());
                expectEquals(10_000, Db.balance(c, Db.ANA));
                expectEquals(5_000, Db.balance(c, Db.BO));

                expectThrows(InsufficientFundsException.class,
                        () -> TransferService.transfer(c, Db.OBRIEN, Db.ANA, 701));
                expectEquals(700, Db.balance(c, Db.OBRIEN));
                expectEquals(10_000, Db.balance(c, Db.ANA));
            }
        });

        // --- the count is the answer, and the catch has to be wide -------------
        check("a transfer to an id that does not exist rolls the debit back", () -> {
            try (Connection c = fresh()) {
                expectThrows(IllegalArgumentException.class,
                        () -> TransferService.transfer(c, Db.ANA, 4_242, 2_500));
                expectEquals(10_000, Db.balance(c, Db.ANA));

                expectThrows(IllegalArgumentException.class,
                        () -> TransferService.transfer(c, 4_242, Db.BO, 100));
                expectEquals(5_000, Db.balance(c, Db.BO));
            }
        });

        check("after a failed transfer the connection is back on autocommit", () -> {
            try (Connection c = fresh()) {
                expectThrows(IllegalArgumentException.class,
                        () -> TransferService.transfer(c, Db.ANA, 4_242, 2_500));
                expectEquals(true, c.getAutoCommit());

                expectThrows(InsufficientFundsException.class,
                        () -> TransferService.transfer(c, Db.BO, Db.ANA, 99_999));
                expectEquals(true, c.getAutoCommit());

                TransferService.transfer(c, Db.ANA, Db.BO, 1);
                expectEquals(true, c.getAutoCommit());
            }
        });

        // --- validate before you dial the database -----------------------------
        check("a silly transfer is refused before any SQL runs at all", () -> {
            Connection dead = Db.open();
            dead.close();
            // Nothing works on a closed connection. If these still throw
            // IllegalArgumentException, the check happened first, which is the point.
            expectThrows(IllegalArgumentException.class, () -> TransferService.transfer(dead, Db.ANA, Db.BO, 0));
            expectThrows(IllegalArgumentException.class, () -> TransferService.transfer(dead, Db.ANA, Db.BO, -250));
            expectThrows(IllegalArgumentException.class, () -> TransferService.transfer(dead, Db.BO, Db.BO, 100));
            expectThrows(IllegalArgumentException.class, () -> TransferService.transfer(dead, Db.OBRIEN, Db.OBRIEN, 5));
            expectThrows(IllegalArgumentException.class, () -> TransferService.deposit(dead, Db.ANA, 0));
            expectThrows(IllegalArgumentException.class, () -> TransferService.deposit(dead, Db.ANA, -7));

            try (Connection c = fresh()) {
                expectThrows(IllegalArgumentException.class, () -> TransferService.transfer(c, Db.ANA, Db.ANA, 100));
                expectThrows(IllegalArgumentException.class, () -> TransferService.deposit(c, 4_242, 100));
                expectEquals(10_000, Db.balance(c, Db.ANA));
                expectEquals(5_000, Db.balance(c, Db.BO));
                expectEquals(700, Db.balance(c, Db.OBRIEN));
            }
        });

        // --- hostile input ------------------------------------------------------
        check("the classic injection string matches nobody, and O'Brien still finds himself", () -> {
            try (Connection c = fresh()) {
                expectEquals(List.of(), AccountSearch.findByOwner(c, "x' OR '1'='1"));
                expectEquals(List.of(), AccountSearch.findByOwner(c, "' OR 1=1 --"));
                expectEquals(List.of(new Account(Db.OBRIEN, "O'Brien", 700)),
                             AccountSearch.findByOwner(c, "O'Brien"));
                expectEquals(List.of(new Account(Db.ANA, "ana", 10_000)),
                             AccountSearch.findByOwner(c, "ana"));
                expectEquals(List.of(), AccountSearch.findByOwner(c, "ANA"));
            }
        });

        check("the values travel as bound parameters: no createStatement, no SQL built with +, the given SQL untouched (this test reads your source)", () -> {
            for (String file : List.of("AccountSearch.java", "TransferService.java")) {
                String src = code(sourceOf(file));
                String flat = masked(src);

                if (flat.contains("createStatement(")) {
                    throw new AssertionError(file + " calls createStatement(): the user's text has to arrive as a value, "
                            + "never as part of the statement. Doubling the quotes yourself is not the fix, it is the bug wearing a hat");
                }
                String glued = gluedSql(src);
                if (glued != null) {
                    throw new AssertionError(file + " concatenates SQL with +: " + glued
                            + "  -- a ? binds a value, and that is the only thing that stops it becoming syntax");
                }
                for (String arg : firstArgs(src, flat, "prepareStatement(")) {
                    if (arg.contains("+") || (arg.startsWith("\"") && !arg.contains("?"))) {
                        throw new AssertionError(file + ": prepareStatement(" + arg + ") is assembled rather than bound");
                    }
                }
                for (String call : List.of("prepareStatement(", "executeQuery(")) {
                    for (int at : occurrences(flat, call)) {
                        if (!insideTryHeader(flat, at)) {
                            throw new AssertionError(file + " line " + lineOf(src, at) + ": this " + call
                                    + ") is not opened by a try-with-resources, so it survives the next exception");
                        }
                    }
                }
            }
            String search = code(sourceOf("AccountSearch.java"));
            if (!search.contains("WHERE owner = ?")) {
                throw new AssertionError("BY_OWNER has lost its ?: that placeholder is the entire defence");
            }
            if (!search.contains("LIKE ? ESCAPE '!'")) {
                throw new AssertionError("BY_PREFIX has lost LIKE ? ESCAPE '!': binding alone does not tame % and _");
            }
        });

        check("a user who types % gets no rows, not everybody's balance", () -> {
            try (Connection c = fresh()) {
                expectEquals(List.of(new Account(Db.ANA, "ana", 10_000)), AccountSearch.findByOwnerPrefix(c, "a"));
                expectEquals(List.of(new Account(Db.OBRIEN, "O'Brien", 700)), AccountSearch.findByOwnerPrefix(c, "O'"));
                expectEquals(3, AccountSearch.findByOwnerPrefix(c, "").size());
                expectEquals(List.of(), AccountSearch.findByOwnerPrefix(c, "%"));
                expectEquals(List.of(), AccountSearch.findByOwnerPrefix(c, "_"));

                // Two more customers, named by somebody with a sense of humour.
                insert(c, 4, "a_b", 11);
                insert(c, 5, "!bang", 22);
                expectEquals(List.of(new Account(4, "a_b", 11)), AccountSearch.findByOwnerPrefix(c, "a_"));
                expectEquals(List.of(new Account(5, "!bang", 22)), AccountSearch.findByOwnerPrefix(c, "!b"));
                expectEquals(2, AccountSearch.findByOwnerPrefix(c, "a").size());
                expectEquals(List.of(), AccountSearch.findByOwnerPrefix(c, "%"));
            }
        });

        // --- twenty threads, one row ---------------------------------------------
        check("20 threads each depositing 10 cents add up to exactly 200", () -> {
            try (Connection c = fresh()) {
                int threads = 20;
                AtomicInteger broke = new AtomicInteger();
                CountDownLatch go = new CountDownLatch(1), done = new CountDownLatch(threads);
                ExecutorService pool = Executors.newFixedThreadPool(threads);
                for (int i = 0; i < threads; i++) {
                    pool.submit(() -> {
                        try (Connection own = Db.open()) {
                            go.await();
                            TransferService.deposit(own, Db.ANA, 10);
                        } catch (Throwable t) {
                            broke.incrementAndGet();
                            System.out.println("         a thread failed: " + t);
                        } finally {
                            done.countDown();
                        }
                    });
                }
                go.countDown();
                if (!done.await(30, TimeUnit.SECONDS)) throw new AssertionError("the deposits never finished");
                pool.shutdown();
                expectEquals(0, broke.get());
                expectEquals(10_200, Db.balance(c, Db.ANA));
                expectEquals(5_000, Db.balance(c, Db.BO));
            }
        });

        System.out.println();
        System.out.println(passed + " / " + (passed + failed) + " tests passed.");
        if (failed > 0) {
            System.out.println("Keep going - make them all green.");
            System.exit(1);
        }
        System.out.println("All green. That transfer is atomic, and it does not care what the user types.");
    }

    // --- fixtures --------------------------------------------------------------

    /** A connection onto the three seeded accounts. */
    static Connection fresh() throws SQLException {
        Connection c = Db.open();
        Db.reset(c);
        return c;
    }

    static void insert(Connection c, long id, String owner, long cents) throws SQLException {
        try (var ps = c.prepareStatement("INSERT INTO account VALUES (?, ?, ?)")) {
            ps.setLong(1, id);
            ps.setString(2, owner);
            ps.setLong(3, cents);
            ps.executeUpdate();
        }
    }

    /** One file of yours, as text. */
    static String sourceOf(String fileName) throws IOException {
        Path p = packageDir().resolve(fileName);
        if (!Files.isRegularFile(p)) throw new AssertionError("expected " + fileName + " next to RunTests.java");
        return Files.readString(p);
    }

    /** A file that only this part has, so the search cannot land in another part's folder. */
    static final String MARKER = "AccountSearch.java";

    /**
     * Where your .java files are. Looked for relative to the working directory AND relative to
     * the class files themselves, because an IDE runs you from the project root while run.sh
     * runs you from this folder. Never silently returns nothing: a check you cannot see is worse
     * than a check that fails.
     */
    static Path packageDir() {
        String pkg = RunTests.class.getPackageName();
        List<Path> roots = new ArrayList<>();
        try {
            var cs = RunTests.class.getProtectionDomain().getCodeSource();
            if (cs != null && cs.getLocation() != null) {
                Path p = Path.of(cs.getLocation().toURI());
                roots.add(Files.isDirectory(p) ? p : p.getParent());
            }
        } catch (Exception ignored) {
            // an exotic class loader; the working directory will have to do
        }
        roots.add(Path.of("").toAbsolutePath());
        for (Path root : roots) {
            Path base = root;
            for (int up = 0; up < 4 && base != null; up++, base = base.getParent()) {
                Path hit = lookFor(base, pkg, 4);
                if (hit != null) return hit;
            }
        }
        throw new AssertionError("cannot find the " + pkg + " sources from " + Path.of("").toAbsolutePath()
                + ": run this part with ./run.sh or .\\run.cmd from its own folder");
    }

    private static Path lookFor(Path base, String pkg, int depth) {
        if (base == null || !Files.isDirectory(base)) return null;
        if (base.getFileName() != null && base.getFileName().toString().equals(pkg)
                && Files.isRegularFile(base.resolve(MARKER))) return base;
        if (depth <= 0) return null;
        try (Stream<Path> kids = Files.list(base)) {
            for (Path k : kids.toList()) {
                String name = k.getFileName().toString();
                if (!Files.isDirectory(k) || name.startsWith(".") || name.equals("lib")) continue;
                Path hit = lookFor(k, pkg, depth - 1);
                if (hit != null) return hit;
            }
        } catch (IOException | UncheckedIOException ignored) {
            // unreadable folder: keep looking elsewhere
        }
        return null;
    }

    // --- enough source reading to tell binding from gluing ---------------------

    /** The source with every comment blanked out, same length, so an offset still means something. */
    static String code(String src) {
        char[] out = src.toCharArray();
        int i = 0, n = src.length();
        while (i < n) {
            char ch = src.charAt(i);
            if (ch == '"' && src.startsWith("\"\"\"", i)) {
                int j = src.indexOf("\"\"\"", i + 3);
                i = j < 0 ? n : j + 3;
            } else if (ch == '"' || ch == '\'') {
                i++;
                while (i < n && src.charAt(i) != ch) i += src.charAt(i) == '\\' ? 2 : 1;
                i++;
            } else if (ch == '/' && i + 1 < n && src.charAt(i + 1) == '/') {
                while (i < n && src.charAt(i) != '\n') out[i++] = ' ';
            } else if (ch == '/' && i + 1 < n && src.charAt(i + 1) == '*') {
                int j = src.indexOf("*/", i + 2);
                j = j < 0 ? n : j + 2;
                while (i < j) { if (out[i] != '\n') out[i] = ' '; i++; }
            } else {
                i++;
            }
        }
        return new String(out);
    }

    /** The same text with the inside of every string blanked, so a bracket in SQL is not a bracket in Java. */
    static String masked(String code) {
        char[] out = code.toCharArray();
        int i = 0, n = code.length();
        while (i < n) {
            char ch = code.charAt(i);
            if (ch == '"' || ch == '\'') {
                i++;
                while (i < n && code.charAt(i) != ch) {
                    if (code.charAt(i) == '\\' && i + 1 < n) out[i++] = ' ';
                    out[i++] = ' ';
                }
                i++;
            } else {
                i++;
            }
        }
        return new String(out);
    }

    static List<Integer> occurrences(String text, String needle) {
        List<Integer> out = new ArrayList<>();
        for (int at = text.indexOf(needle); at >= 0; at = text.indexOf(needle, at + 1)) out.add(at);
        return out;
    }

    /** The first argument of every call to this method, as you wrote it. */
    static List<String> firstArgs(String code, String flat, String call) {
        List<String> out = new ArrayList<>();
        for (int at : occurrences(flat, call)) {
            int i = at + call.length(), start = i, depth = 1;
            while (i < flat.length() && depth > 0) {
                char ch = flat.charAt(i);
                if (ch == '(') depth++;
                else if (ch == ')') { depth--; if (depth == 0) break; }
                else if (ch == ',' && depth == 1) break;
                i++;
            }
            out.add(code.substring(start, Math.min(i, code.length())).trim());
        }
        return out;
    }

    /** Is this offset inside the bracket of a try-with-resources? */
    static boolean insideTryHeader(String flat, int at) {
        Matcher m = Pattern.compile("\\btry\\s*\\(").matcher(flat);
        while (m.find()) {
            int i = m.end() - 1, depth = 0;
            for (; i < flat.length(); i++) {
                char ch = flat.charAt(i);
                if (ch == '(') depth++;
                else if (ch == ')' && --depth == 0) break;
            }
            if (at > m.start() && at < i) return true;
        }
        return false;
    }

    /** A SQL string with a + stuck to it, which is the whole bug in one pattern. */
    static String gluedSql(String code) {
        Matcher lit = Pattern.compile("\"(?:\\\\.|[^\"\\\\])*\"").matcher(code);
        Pattern sql = Pattern.compile("(?i)\\b(select|insert|update|delete|from|where|values|like)\\b");
        while (lit.find()) {
            if (!sql.matcher(lit.group()).find()) continue;
            String before = code.substring(Math.max(0, lit.start() - 4), lit.start()).trim();
            String after = code.substring(lit.end(), Math.min(code.length(), lit.end() + 4)).trim();
            if (before.endsWith("+") || after.startsWith("+")) return lit.group();
        }
        return null;
    }

    static int lineOf(String src, int at) {
        return (int) src.substring(0, Math.min(at, src.length())).chars().filter(ch -> ch == '\n').count() + 1;
    }

    // --- tiny test harness (no JUnit needed) ----------------------------------
    interface Body { void run() throws Throwable; }

    static void check(String name, Body b) {
        try { b.run(); passed++; System.out.println("[PASS] " + name); }
        catch (Throwable t) { failed++; System.out.println("[FAIL] " + name + "\n         " + t); }
    }

    static void expectEquals(long want, long got) {
        if (want != got) throw new AssertionError("expected " + want + " but got " + got);
    }

    static void expectEquals(Object want, Object got) {
        if (!Objects.equals(want, got)) throw new AssertionError("expected [" + want + "] but got [" + got + "]");
    }

    static <T extends Throwable> T expectThrows(Class<T> expected, Body b) {
        try {
            b.run();
        } catch (Throwable t) {
            if (expected.isInstance(t)) return expected.cast(t);
            throw new AssertionError("expected " + expected.getSimpleName() + " but got " + t);
        }
        throw new AssertionError("expected " + expected.getSimpleName() + " but nothing was thrown");
    }
}
